<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="fr" xml:lang="fr"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>5&nbsp; Comparaison de deux groupes – Analyser des données avec R</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./regressions.html" rel="next">
<link href="./bivariate_analyses.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-9e3e5b9121e68b3f077afb32f2c64d95.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Pas de résultats",
    "search-matching-documents-text": "documents trouvés",
    "search-copy-link-title": "Copier le lien vers la recherche",
    "search-hide-matches-text": "Cacher les correspondances additionnelles",
    "search-more-match-text": "correspondance de plus dans ce document",
    "search-more-matches-text": "correspondances de plus dans ce document",
    "search-clear-button-title": "Effacer",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Annuler",
    "search-submit-button-title": "Envoyer",
    "search-label": "Recherche"
  }
}</script>
<link href="site_libs/tabwid-1.1.3/tabwid.css" rel="stylesheet">

<script src="site_libs/tabwid-1.1.3/tabwid.js"></script>


  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Basculer la barre latérale" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./univariate_analyses.html">Analyses descriptives</a></li><li class="breadcrumb-item"><a href="./two_group_comparison.html"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Comparaison de deux groupes</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Basculer la barre latérale" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Recherche" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Analyser des données avec R</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://github.com/pydemull/Analyser-des-donnees-avec-R" title="Code source" class="quarto-navigation-tool px-1" aria-label="Code source"><i class="bi bi-github"></i></a>
    <a href="./Analyser-des-données-avec-R.pdf" title="Download PDF" class="quarto-navigation-tool px-1" aria-label="Download PDF"><i class="bi bi-file-pdf"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Basculer en mode lecteur">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Recherche"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Appropriation de R et RStudio</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Basculer la section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prerequisite.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Prérequis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data_manipulation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Importation et manipulation d’une base de données</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Analyses descriptives</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Basculer la section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./univariate_analyses.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Analyses univariées</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bivariate_analyses.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Analyses bivariées</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./two_group_comparison.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Comparaison de deux groupes</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./regressions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Régressions</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Analyses inférentielles</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Basculer la section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./statistical_theory.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Prérequis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./categorical_var_tests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Tests statistiques pour des variables qualitatives</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Références</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Sommaire</h2>
   
  <ul>
  <li><a href="#comparaison-sur-une-variable-quantitative" id="toc-comparaison-sur-une-variable-quantitative" class="nav-link active" data-scroll-target="#comparaison-sur-une-variable-quantitative"><span class="header-section-number">5.1</span> Comparaison sur une variable quantitative</a>
  <ul class="collapse">
  <li><a href="#notions" id="toc-notions" class="nav-link" data-scroll-target="#notions"><span class="header-section-number">5.1.1</span> Notions</a></li>
  <li><a href="#comparer-deux-groupes-non-appariés" id="toc-comparer-deux-groupes-non-appariés" class="nav-link" data-scroll-target="#comparer-deux-groupes-non-appariés"><span class="header-section-number">5.1.2</span> Comparer deux groupes non appariés</a></li>
  <li><a href="#comparer-deux-groupes-appariés" id="toc-comparer-deux-groupes-appariés" class="nav-link" data-scroll-target="#comparer-deux-groupes-appariés"><span class="header-section-number">5.1.3</span> Comparer deux groupes appariés</a></li>
  </ul></li>
  <li><a href="#comparaison-sur-une-variable-qualitative" id="toc-comparaison-sur-une-variable-qualitative" class="nav-link" data-scroll-target="#comparaison-sur-une-variable-qualitative"><span class="header-section-number">5.2</span> Comparaison sur une variable qualitative</a>
  <ul class="collapse">
  <li><a href="#étudier-graphiquement-la-comparaison-2" id="toc-étudier-graphiquement-la-comparaison-2" class="nav-link" data-scroll-target="#étudier-graphiquement-la-comparaison-2"><span class="header-section-number">5.2.1</span> Étudier graphiquement la comparaison</a></li>
  <li><a href="#étudier-numériquement-la-comparaison-2" id="toc-étudier-numériquement-la-comparaison-2" class="nav-link" data-scroll-target="#étudier-numériquement-la-comparaison-2"><span class="header-section-number">5.2.2</span> Étudier numériquement la comparaison</a></li>
  </ul></li>
  <li><a href="#résumé" id="toc-résumé" class="nav-link" data-scroll-target="#résumé"><span class="header-section-number">5.3</span> Résumé</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/pydemull/Analyser-des-donnees-avec-R/edit/master/two_group_comparison.qmd" class="toc-action"><i class="bi bi-github"></i>Modifier cette page</a></li><li><a href="https://github.com/pydemull/Analyser-des-donnees-avec-R/issues/new" class="toc-action"><i class="bi empty"></i>Faire part d'un problème</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./univariate_analyses.html">Analyses descriptives</a></li><li class="breadcrumb-item"><a href="./two_group_comparison.html"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Comparaison de deux groupes</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Comparaison de deux groupes</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Lorsqu’on compare des données quantitatives ou qualitatives en fonction des modalités d’une variable qualitative, on peut avoir des données qui sont non appariées (étude de type <em>between-subject design</em> en anglais) ou appariées (étude de type <em>within-subject design</em> en anglais). Avoir des données non appariées signifie que les données n’appartiennent pas aux mêmes individus. Un exemple simple, pour ce premier cas, peut être la comparaison de la taille entre les hommes et les femmes. Dans ce cas, les données quantitatives de taille selon les modalités de sexe proviendront forcément d’individus différents et ne formeront donc pas des paires. S’agissant des cas de données appariées, ils se retrouvent dans les études où plusieurs individus sont évalués plusieurs fois dans des conditions similaires ou différentes et que l’on cherche à comparer. En sciences du sport, un exemple relativement classique est de tester la performance d’endurance (variable quantitative) en ayant pris (condition de test) ou non (condition contrôle) une substance potentiellement ergogénique, la prise de substance ou non étant les modalités d’une même variable qualitative de type condition. Dans ce cas là, tous les individus auront des données dans les deux conditions et ces données seront donc appariées (dépendantes).</p>
<p>La notion d’appariement ou non peut bien sûr s’étendre aux cas de figure où il y aurait plus que deux groupes de valeurs à comparer. Toutefois, les procédures graphiques et calculatoires sont différentes selon que l’on a deux groupes ou plus. Ce chapitre s’intéresse seulement à la comparaison de deux groupes.</p>
<section id="comparaison-sur-une-variable-quantitative" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="comparaison-sur-une-variable-quantitative"><span class="header-section-number">5.1</span> Comparaison sur une variable quantitative</h2>
<section id="notions" class="level3" data-number="5.1.1">
<h3 data-number="5.1.1" class="anchored" data-anchor-id="notions"><span class="header-section-number">5.1.1</span> Notions</h3>
<section id="différences-de-moyennes-standardisées" class="level4" data-number="5.1.1.1">
<h4 data-number="5.1.1.1" class="anchored" data-anchor-id="différences-de-moyennes-standardisées"><span class="header-section-number">5.1.1.1</span> Différences de moyennes standardisées</h4>
<p>Les statistiques qui sont classiquement envisagées pour chiffrer les comparaisons entre deux groupes de valeurs numériques sont les différences de moyennes (associées respectivement aux deux groupes étudiés) standardisées, c’est-à-dire normalisées (ou, plus concrètement, divisées) par le degré d’hétérogénéité interindividuelle (une sorte d’écart-type) pour la variable étudiée <span class="citation" data-cites="lakensCalculatingReportingEffect2013">(<a href="references.html#ref-lakensCalculatingReportingEffect2013" role="doc-biblioref">Lakens, 2013</a>)</span>. Ces statistiques sont inhérentes aux tests <span class="math inline">\(t\)</span> de Student et de Welch. Les différences de moyennes standardisées, qui de par leurs calculs sont sans unité, favorisent la possibilité de porter un jugement sur la grandeur relative de la différence de moyennes entre les groupes comparés et la possibilité de comparer cette différence avec celles observées dans d’autres études, en particulier celles traitant de thématiques différentes avec des variables et unités correspondantes différentes. Cela étant dit, il est important d’avoir en tête que la grandeur d’une différence de moyennes standardisée ne renseigne pas forcément directement sur l’importance pratique que la différence inter-groupe observée dans une étude pourrait avoir sur le terrain. Par exemple, une grande ou une petite différence standardisée pourraient correspondre à une même différence absolue entre deux moyennes (par exemple une distance en mètres) selon que le degré d’hétérogénéité interindividuelle dans l’étude est faible ou élevé, respectivement.</p>
<p>En principe, les différences de moyennes standardisées sont valides pour pouvoir faire des inférences dans une population seulement lorsque la variable étudiée suit une loi normale (soit pour chacun des deux groupes non appariés comparés, soit pour les différences intra-individu en cas de groupes appariés) et que les variances des deux groupes comparés (en cas de groupes non appariés) sont relativement identiques. Lorsqu’une de ces conditions n’est pas respectée, il est possible que l’estimation faite à partir de l’échantillon pour caractériser la population soit en général très imprécise. Aussi, dans ces cas là, mieux vaut utiliser une version dite “robuste” des différences de moyennes standardisées, tel qu’en procédant à une winsorisation des données avant de procéder aux calculs classiques (i.e., on remplace, dans les variables d’origine, les valeurs correspondant aux 20 % les plus faibles et celles correspondant aux 20 % les plus élevés par respectivement la valeur la plus basse avant les 20 % les plus faibles et la valeur la plus haute avant les 20 % les plus élevés) <span class="citation" data-cites="liEffectSizeMeasures2016">(<a href="references.html#ref-liEffectSizeMeasures2016" role="doc-biblioref">Li, 2016</a>)</span>. Une autre approche consiste à utiliser des statistiques qui ne font pas d’hypothèse sur la manière dont sont distribuées les données dans la population d’origine pour les groupes à comparer, telles que la corrélation bisériale des rangs qui est à associer aux tests statistiques de somme des rangs et des rangs signés de Wilcoxon. Enfin, une autre approche robuste qui peut être associée à divers tests de comparaison de deux groupes est la probabilité de supériorité. Ces deux dernières approches sont présentées plus en détails ci-après.</p>
</section>
<section id="dominance" class="level4" data-number="5.1.1.2">
<h4 data-number="5.1.1.2" class="anchored" data-anchor-id="dominance"><span class="header-section-number">5.1.1.2</span> Dominance</h4>
<p>La notion de dominance d’un groupe par rapport à un autre est à privilégier à la classique différence de moyennes standardisée lorsque les conditions d’analyse rendent cette statistique imprécise (i.e., absence de normalité en cas de groupes non appariés ou appariés, hétérogénéité des variances en cas de groupes non appariés). La corrélation bisériale des rangs (<span class="math inline">\(r_{rb}\)</span>) est un moyen de caractériser la dominance d’un groupe par rapport à un autre. Cette statistique, située entre -1 et 1, est telle que des valeurs plus élevées indiquent que davantage de valeurs d’un groupe sont supérieures à celles de l’autre groupe. Une valeur de −1 signifie que toutes les observations dans le second groupe sont supérieures à celles du premier, tandis qu’une valeur de +1 signifie que toutes les observations dans le premier groupe sont supérieures à celles du second (source: <a href="https://easystats.github.io/effectsize/articles/standardized_differences.html#dominance-effect-sizes">site du package {effectsize}</a>).</p>
</section>
<section id="langage-commun" class="level4" data-number="5.1.1.3">
<h4 data-number="5.1.1.3" class="anchored" data-anchor-id="langage-commun"><span class="header-section-number">5.1.1.3</span> Langage commun</h4>
<p>L’approche du langage commun consiste à caractériser une différence entre deux groupes en utilisant des termes relativement simples. Un exemple est de présenter la probabilité de supériorité, c’est-à-dire le % de chances (ou la probabilité) qu’un individu pris au hasard dans un groupe ait une valeur plus élevée qu’un individu pris au hasard dans le second groupe. D’autres statistiques peuvent aussi être calculées, notamment : le <span class="math inline">\(U_{1}\)</span> de Cohen, qui désigne la proportion des deux distributions sans superposition des individus ; ou encore le <span class="math inline">\(U_{3}\)</span> de Cohen, qui désigne la proportion d’un groupe qui a des valeurs plus faibles que la médiane de l’autre groupe (source: <a href="https://easystats.github.io/effectsize/articles/standardized_differences.html#dominance-effect-sizes">site du package {effectsize}</a>).</p>
</section>
</section>
<section id="comparer-deux-groupes-non-appariés" class="level3" data-number="5.1.2">
<h3 data-number="5.1.2" class="anchored" data-anchor-id="comparer-deux-groupes-non-appariés"><span class="header-section-number">5.1.2</span> Comparer deux groupes non appariés</h3>
<section id="étudier-graphiquement-la-comparaison" class="level4" data-number="5.1.2.1">
<h4 data-number="5.1.2.1" class="anchored" data-anchor-id="étudier-graphiquement-la-comparaison"><span class="header-section-number">5.1.2.1</span> Étudier graphiquement la comparaison</h4>
<p>La <a href="#fig-raindcloudplotsBivUnpaired1" class="quarto-xref">Figure&nbsp;<span>5.1</span></a>, qui est associée au bloc de code ci-dessous, montre un graphique approprié pour des données non appariées.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Configuration du jeu de données pour l'exemple avec données non appariées.</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Il s'agit ici d'obtenir le jeu de données `iris` avec seulement deux modalités  </span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co"># de la variable `Species`, cela en enlevant la modalité `virginica`.</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>iris_two_species <span class="ot">&lt;-</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  iris <span class="sc">|&gt;</span> </span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Species <span class="sc">!=</span> <span class="st">"virginica"</span>) <span class="sc">|&gt;</span> </span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Species =</span> <span class="fu">factor</span>(Species, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"setosa"</span>, <span class="st">"versicolor"</span>)))</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(iris_two_species)</span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Sepal.Length Sepal.Width Petal.Length Petal.Width Species
1          5.1         3.5          1.4         0.2  setosa
2          4.9         3.0          1.4         0.2  setosa
3          4.7         3.2          1.3         0.2  setosa
4          4.6         3.1          1.5         0.2  setosa
5          5.0         3.6          1.4         0.2  setosa
6          5.4         3.9          1.7         0.4  setosa</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Création du graphique</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> iris_two_species, <span class="fu">aes</span>(<span class="at">x =</span> Species, <span class="at">y =</span> Sepal.Length)) <span class="sc">+</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_rain</span>(<span class="at">point.args =</span> rlang<span class="sc">::</span><span class="fu">list2</span>(<span class="at">alpha =</span> <span class="fl">0.3</span>)) <span class="sc">+</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">geom =</span> <span class="st">"errorbar"</span>,</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">fun.data =</span> <span class="st">"mean_sdl"</span>,</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">fun.args =</span> <span class="fu">list</span>(<span class="at">mult =</span> <span class="dv">1</span>),</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">linewidth =</span> <span class="fl">1.1</span>, </span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">width =</span> <span class="fl">0.06</span></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">+</span> </span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">geom =</span> <span class="st">"point"</span>,</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">fun =</span> <span class="st">"mean"</span>, </span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">size =</span> <span class="dv">3</span></span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>    )</span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-raindcloudplotsBivUnpaired1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-raindcloudplotsBivUnpaired1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="two_group_comparison_files/figure-html/fig-raindcloudplotsBivUnpaired1-1.png" class="img-fluid figure-img" style="width:90.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-raindcloudplotsBivUnpaired1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.1: Exemple de graphique pour une comparaison de deux groupes de valeurs non appariés (indépendants)
</figcaption>
</figure>
</div>
</div>
</div>
<p>On note que pour montrer les moyennes et écarts-types sur la <a href="#fig-raindcloudplotsBivUnpaired1" class="quarto-xref">Figure&nbsp;<span>5.1</span></a>, il a fallu utiliser la fonction <code>stat_summary()</code> du package <code>{Hmisc}</code> (qui est chargé automatiquement lors du chargement de <code>ggplot2</code> après que <code>{Hmisc}</code> ait été installé). Cette fonction sert à visualiser un résumé statistique. Pour montrer les moyennes, on utilise <code>fun = "mean"</code>, alors que pour montrer des écarts-types, on utilise <code>fun.data = "mean_sdl"</code>. Pour les écarts-types, il faut ajouter <code>fun.args = list(mult = 1)</code> pour bien montrer une barre d’erreur ne correspondant qu’à un seul multiple de l’écart-type, car par défaut c’est deux fois l’écart-type qui est montré. On peut choisir la forme avec laquelle présenter le résumé statistique grâce à l’argument <code>geom</code>.</p>
</section>
<section id="étudier-numériquement-la-comparaison" class="level4" data-number="5.1.2.2">
<h4 data-number="5.1.2.2" class="anchored" data-anchor-id="étudier-numériquement-la-comparaison"><span class="header-section-number">5.1.2.2</span> Étudier numériquement la comparaison</h4>
<section id="différences-de-moyennes-standardisées-1" class="level5" data-number="5.1.2.2.1">
<h5 data-number="5.1.2.2.1" class="anchored" data-anchor-id="différences-de-moyennes-standardisées-1"><span class="header-section-number">5.1.2.2.1</span> Différences de moyennes standardisées</h5>
<section id="d_s-et-d_av-de-cohen" class="level6" data-number="5.1.2.2.1.1">
<h6 data-number="5.1.2.2.1.1" class="anchored" data-anchor-id="d_s-et-d_av-de-cohen"><span class="header-section-number">5.1.2.2.1.1</span> <span class="math inline">\(d_{s}\)</span> et <span class="math inline">\(d_{av}\)</span> de Cohen</h6>
<p>Classiquement, l’indice statistique utilisé pour calculer une différence de moyennes de manière standardisée entre deux groupes indépendants, à partir d’échantillons de population, est le <span class="math inline">\(d_{s}\)</span> de Cohen. Cette statistique se calcule en faisant la différence entre les moyennes des deux groupes à comparer, et en divisant cette différence par l’écart-type combiné (ou commun) des deux groupes. Ce calcul est montré ci-dessous :</p>
<p><span class="math display">\[d_{s} = \frac{\overline{X}_{1} - \overline{X}_{2}} {\sqrt{\frac{(N_{1} - 1) \hat{\sigma}_{1}^2 + (N_{2} - 1) \hat{\sigma}_{2}^2} {N_{1} + N_{2} - 2}}},\]</span></p>
<p>avec <span class="math inline">\(\overline{X}_{1}\)</span> et <span class="math inline">\(\overline{X}_{2}\)</span> les moyennes des deux groupes comparés, <span class="math inline">\(N_{1}\)</span> et <span class="math inline">\(N_{2 }\)</span> les effectifs respectifs des deux groupes comparés, et <span class="math inline">\(\hat{\sigma}_{1}^2\)</span> et <span class="math inline">\(\hat{\sigma}_{2}^2\)</span> les variances respectives des deux groupes comparés. On peut remarquer qu’au dénominateur, la variance d’un groupe donné est multipliée par un coefficient calculé à partir de l’effectif du groupe, cela pour que le poids de la variance d’un groupe dans le calcul final soit ajusté par rapport à la taille du groupe. Dans R, si l’on voulait calculer <span class="math inline">\(d_s\)</span> manuellement, cela donnerait ceci (à partir du jeu de données <code>iris_two_species</code>) :</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcul des paramètres</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>X1 <span class="ot">&lt;-</span> iris_two_species <span class="sc">|&gt;</span> <span class="fu">filter</span>(Species <span class="sc">==</span> <span class="st">"setosa"</span>) <span class="sc">|&gt;</span> <span class="fu">pull</span>(Sepal.Length) <span class="sc">|&gt;</span> <span class="fu">mean</span>()</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>X2 <span class="ot">&lt;-</span> iris_two_species <span class="sc">|&gt;</span> <span class="fu">filter</span>(Species <span class="sc">==</span> <span class="st">"versicolor"</span>) <span class="sc">|&gt;</span> <span class="fu">pull</span>(Sepal.Length) <span class="sc">|&gt;</span> <span class="fu">mean</span>()</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>SD1 <span class="ot">&lt;-</span> iris_two_species <span class="sc">|&gt;</span> <span class="fu">filter</span>(Species <span class="sc">==</span> <span class="st">"setosa"</span>) <span class="sc">|&gt;</span> <span class="fu">pull</span>(Sepal.Length) <span class="sc">|&gt;</span> <span class="fu">sd</span>()</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>SD2 <span class="ot">&lt;-</span> iris_two_species <span class="sc">|&gt;</span> <span class="fu">filter</span>(Species <span class="sc">==</span> <span class="st">"versicolor"</span>) <span class="sc">|&gt;</span> <span class="fu">pull</span>(Sepal.Length) <span class="sc">|&gt;</span> <span class="fu">sd</span>()</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>N1 <span class="ot">&lt;-</span> iris_two_species <span class="sc">|&gt;</span> <span class="fu">filter</span>(Species <span class="sc">==</span> <span class="st">"setosa"</span>) <span class="sc">|&gt;</span> <span class="fu">pull</span>(Sepal.Length) <span class="sc">|&gt;</span> <span class="fu">length</span>()</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>N2 <span class="ot">&lt;-</span> iris_two_species <span class="sc">|&gt;</span> <span class="fu">filter</span>(Species <span class="sc">==</span> <span class="st">"versicolor"</span>) <span class="sc">|&gt;</span> <span class="fu">pull</span>(Sepal.Length) <span class="sc">|&gt;</span> <span class="fu">length</span>()</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcul de ds</span></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>ds <span class="ot">&lt;-</span> (X1 <span class="sc">-</span> X2) <span class="sc">/</span> <span class="fu">sqrt</span>(((N1<span class="dv">-1</span>) <span class="sc">*</span> SD1<span class="sc">^</span><span class="dv">2</span> <span class="sc">+</span> (N2<span class="dv">-1</span>) <span class="sc">*</span> SD2<span class="sc">^</span><span class="dv">2</span>) <span class="sc">/</span> (N1<span class="sc">+</span>N2<span class="dv">-2</span>))</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>ds</span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -2.104197</code></pre>
</div>
</div>
<p>Heureusement, le <span class="math inline">\(d_{s}\)</span> de Cohen peut être facilement calculé à l’aide de la fonction <code>cohens_d()</code> du package <code>{effectsize}</code>, qui nécessite d’être installé puis chargé avant d’être utilisé :</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(effectsize)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>ds <span class="ot">&lt;-</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cohens_d</span>(</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>    Sepal.Length <span class="sc">~</span> Species,</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> iris_two_species,</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">paired =</span> <span class="cn">FALSE</span>,</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">pooled_sd =</span> <span class="cn">TRUE</span></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>ds</span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Cohen's d |         95% CI
--------------------------
-2.10     | [-2.59, -1.61]

- Estimated using pooled SD.</code></pre>
</div>
</div>
<p>Dans cet exemple, on remarque qu’on a bien cherché à savoir comment les données de la variable <code>Sepal.Length</code> pouvaient différer en fonction (<code>~</code>) des modalités de la variable <code>Species</code>. Si la fonction nous donne un résultat, il faut toutefois bien faire attention au sens du calcul qui a été réalisé. Configurée de la sorte, la fonction <code>cohens_d()</code> réalise la différence <strong>modalité 1 - modalité 2</strong>. Il faut donc savoir quelle est la modalité 1 et quelle est la modalité 2 dans la variable <code>Species</code> pour ensuite pouvoir interpréter le signe du résultat, qui est négatif ici avec la valeur de -2.10. Pour ce faire, on peut utiliser la fonction <code>levels()</code> :</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(iris_two_species<span class="sc">$</span>Species)</span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "setosa"     "versicolor"</code></pre>
</div>
</div>
<p>L’ordre des modalités affichées nous indique que <code>setosa</code> est la modalité 1, et que <code>versicolor</code> est la modalité 2. Par conséquent, le <span class="math inline">\(d_{s}\)</span> de Cohen de -2.10 obtenu plus haut indique que la longueur des sépales (<code>Sepal.Length</code>) pour l’espèce <code>setosa</code> est inférieure à celles des sépales de l’espèce <code>versicolor</code>. Cette interprétation est en cohérence avec le graphique réalisé au préalable (cf. <a href="#fig-raindcloudplotsBivUnpaired1" class="quarto-xref">Figure&nbsp;<span>5.1</span></a>). Si l’on avait voulu avoir le calcul inverse (<code>versicolor</code> - <code>setosa</code>), il aurait fallu reconfigurer l’ordre des modalités, par exemple à l’aide de la fonction <code>fct_relevel()</code> du package <code>{forcats}</code> comme montré à la fin du chapitre 3.</p>
<p>De manière importante, le calcul de <span class="math inline">\(d_s\)</span> à partir d’un échantillon en vue d’avoir une estimation dans la population suppose que les variances des deux groupes dans la population d’intérêt soient similaires. Si cette supposition n’est pas valide ou est non désirée, alors il peut être préconisé de calculer un autre indicateur appelé <span class="math inline">\(d_{av}\)</span> (voir explications <a href="https://aaroncaldwell.us/TOSTERpkg/articles/SMD_calcs.html">ici</a>), lequel consiste à diviser la différence de moyennes par un écart-type moyen :</p>
<p><span class="math display">\[d_{av} = \frac{\overline{X}_{1} - \overline{X}_{2}} {\sqrt{\frac{\hat{\sigma}_{1}^2 + \hat{\sigma}_{2}^2} {2}}}\]</span></p>
<p>En repartant des paramètres calculés précédemment, on peut manuellement obtenir cet indice comme ceci :</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcul de dav</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>dav <span class="ot">&lt;-</span> (X1 <span class="sc">-</span> X2) <span class="sc">/</span> <span class="fu">sqrt</span>((SD1<span class="sc">^</span><span class="dv">2</span> <span class="sc">+</span> SD2<span class="sc">^</span><span class="dv">2</span>) <span class="sc">/</span> <span class="dv">2</span>)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>dav</span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -2.104197</code></pre>
</div>
</div>
<p>On peut obtenir le <span class="math inline">\(d_{av}\)</span> avec le package <code>{effectsize}</code> comme ceci (avec <code>pooled_sd = FALSE</code>) :</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>dav <span class="ot">&lt;-</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cohens_d</span>(</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>    Sepal.Length <span class="sc">~</span> Species,</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> iris_two_species,</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">paired =</span> <span class="cn">FALSE</span>,</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">pooled_sd =</span> <span class="cn">FALSE</span></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>dav</span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Cohen's d |         95% CI
--------------------------
-2.10     | [-2.60, -1.60]

- Estimated using un-pooled SD.</code></pre>
</div>
</div>
<p>On note que les valeurs de <span class="math inline">\(d_s\)</span> et de <span class="math inline">\(d_{av}\)</span> ne changent pas dans nos exemples car chaque modalité de la variable <code>Species</code> est associée au même nombre d’individus, ce qui revient à faire des calculs similaires pour les deux indices statistiques obtenus jusqu’à présent.</p>
<p>Malheureusement, il se trouve que <span class="math inline">\(d\)</span> (<span class="math inline">\(d_s\)</span> ou <span class="math inline">\(d_{av}\)</span>) est indicateur qui est biaisé positivement lorsqu’il s’agit d’estimer la différence de moyennes standardisée à l’échelle de la population d’intérêt. Par « biaisé positivement », il faut comprendre que si une multitude d’études s’intéressait à calculer <span class="math inline">\(d\)</span> et qu’on faisait la moyenne des résultats trouvés, alors on aurait une surestimation de la magnitude de la valeur de <span class="math inline">\(d\)</span> dans la population (il s’agit d’un fait qui peut être démontré avec des simulations sur un ordinateur), cela notamment dans le cas où les études utiliseraient de petits échantillons (N &lt; 20), selon Hedges et Okins (1985) cités par Lakens <span class="citation" data-cites="lakensCalculatingReportingEffect2013">(<a href="references.html#ref-lakensCalculatingReportingEffect2013" role="doc-biblioref">2013</a>)</span>.</p>
</section>
<section id="g_s-et-g_av-de-hedges" class="level6" data-number="5.1.2.2.1.2">
<h6 data-number="5.1.2.2.1.2" class="anchored" data-anchor-id="g_s-et-g_av-de-hedges"><span class="header-section-number">5.1.2.2.1.2</span> <span class="math inline">\(g_{s}\)</span> et <span class="math inline">\(g_{av}\)</span> de Hedges</h6>
<p>Pour régler le problème de biais que pose le <span class="math inline">\(d\)</span> de Cohen, un autre indicateur statistique a été proposé : le <span class="math inline">\(g\)</span> de Hedges. Il s’agit en réalité du <span class="math inline">\(d\)</span> de Cohen, mais qu’on modifie grâce à l’utilisation d’un facteur de correction. Une approximation de <span class="math inline">\(g\)</span> est montrée ci-dessous <span class="citation" data-cites="lakensCalculatingReportingEffect2013">(<a href="references.html#ref-lakensCalculatingReportingEffect2013" role="doc-biblioref">2013</a>)</span> :</p>
<p><span class="math display">\[g = d (1 - \frac{3}{4(N_{1} + N_{2}) - 9}),\]</span></p>
<p>avec <span class="math inline">\(d\)</span> le <span class="math inline">\(d_s\)</span> ou le <span class="math inline">\(d_{av}\)</span> de Cohen, et <span class="math inline">\(N_{1}\)</span> et <span class="math inline">\(N_{2}\)</span> les effectifs respectifs des deux groupes comparés. En réalité, le calcul exact du facteur de correction est relativement complexe, et est montré avec l’équation ci-dessous <span class="citation" data-cites="kelleyEffectsNonnormalDistributions2005">(<a href="references.html#ref-kelleyEffectsNonnormalDistributions2005" role="doc-biblioref">Kelley, 2005</a>)</span> :</p>
<p><span class="math display">\[g =  d \frac{\Gamma(\frac{df}{2})}{\sqrt{\frac{df}{2}\Gamma(\frac{df-1}{2})}} \]</span></p>
<p>avec <span class="math inline">\(\Gamma\)</span> la loi Gamma, et <span class="math inline">\(df\)</span> ce qu’on appelle le nombre de degrés de liberté (qui est ici égal au nombre total d’individus moins 2). Dans les faits, les différences entre <span class="math inline">\(d\)</span> et <span class="math inline">\(g\)</span> sont relativement modestes, surtout avec <span class="math inline">\(N\)</span> &gt; 20 dans les groupes.</p>
<p>Dans R, le <span class="math inline">\(g_{s}\)</span> de Hedges lié à un échantillon de population peut être calculé à l’aide de la fonction <code>hedges_g()</code> du package <code>{effectsize}</code> :</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>gs <span class="ot">&lt;-</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">hedges_g</span>(</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>    Sepal.Length <span class="sc">~</span> Species,</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> iris_two_species,</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">paired =</span> <span class="cn">FALSE</span>,</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">pooled_sd =</span> <span class="cn">TRUE</span></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>gs</span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Hedges' g |         95% CI
--------------------------
-2.09     | [-2.57, -1.60]

- Estimated using pooled SD.</code></pre>
</div>
</div>
<p>Ici, la valeur ne change pas beaucoup par rapport à <span class="math inline">\(d_s\)</span> car l’effectif n’est pas si petit que cela (<span class="math inline">\(N_{1}\)</span> + <span class="math inline">\(N_{2}\)</span> = 100 ici, ce qui fait que la correction appliquée au <span class="math inline">\(d_{s}\)</span> de Cohen est minime).</p>
<p>Le <span class="math inline">\(g_{av}\)</span> de Hedges lié à un échantillon de population peut aussi être calculé à l’aide de la fonction <code>hedges_g()</code> du package <code>{effectsize}</code> (avec <code>pooled_sd = FALSE</code>) :</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>gav <span class="ot">&lt;-</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">hedges_g</span>(</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>    Sepal.Length <span class="sc">~</span> Species,</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> iris_two_species,</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">paired =</span> <span class="cn">FALSE</span>,</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">pooled_sd =</span> <span class="cn">FALSE</span></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>gav</span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Hedges' g |         95% CI
--------------------------
-2.09     | [-2.58, -1.58]

- Estimated using un-pooled SD.</code></pre>
</div>
</div>
<p>Par principe, <strong>il pourrait être recommandé de toujours utiliser le <span class="math inline">\(g\)</span> (<span class="math inline">\(g_s\)</span> ou <span class="math inline">\(g_{av}\)</span>) de Hedges</strong> <span class="citation" data-cites="lakensCalculatingReportingEffect2013">(<a href="references.html#ref-lakensCalculatingReportingEffect2013" role="doc-biblioref">Lakens, 2013</a>)</span>.</p>
</section>
<section id="delta-de-glass" class="level6" data-number="5.1.2.2.1.3">
<h6 data-number="5.1.2.2.1.3" class="anchored" data-anchor-id="delta-de-glass"><span class="header-section-number">5.1.2.2.1.3</span> Delta de Glass</h6>
<p>Dans certains cas où l’on souhaiterait comparer les scores de deux groupes indépendants pour tester l’effet de deux conditions expérimentales différentes, l’expérimentation en tant que telle peut influencer, au-delà de la moyenne, l’écart-type de la variable réponse dans un des deux groupes. On peut se trouver dans ce genre de situation lorsque l’on compare les données post-programme d’un groupe entraîné ou traité à celles d’un groupe contrôle. En effet, le groupe entraîné/traité peut voir son écart-type changé au terme d’un programme en raison d’une réponse individuelle hétérogène à ce programme, ce qui ne sera pas en principe le cas du groupe contrôle. Dans ce genre de situations, des indices statistiques autres que le <span class="math inline">\(d\)</span> de Cohen ou le <span class="math inline">\(g\)</span> de Hedges mériteraient d’être calculés, tels que le delta (<span class="math inline">\(\Delta\)</span>) de Glass <span class="citation" data-cites="lakensCalculatingReportingEffect2013">(<a href="references.html#ref-lakensCalculatingReportingEffect2013" role="doc-biblioref">Lakens, 2013</a>)</span> :</p>
<p><span class="math display">\[\Delta = \frac{\overline{X}_{1} - \overline{X}_{2}} {\hat{\sigma}_{2}}\]</span></p>
<p>Le calcul du <span class="math inline">\(\Delta\)</span> de Glass est dans l’idée le même que celui du <span class="math inline">\(d\)</span> de Cohen, sauf que la différence entre les moyennes des deux groupes n’est pas divisée par un écart-type lié aux deux groupes, mais par l’écart-type d’un seul des deux groupes, qui serait en principe celui qui représenterait la condition contrôle ou la condition de référence. Une pratique souvent recommandée pour comparer dans ce genre de situation les scores post-programme de deux groupes (un groupe entraîné/traité et un groupe contrôle) serait d’utiliser l’écart-type des scores du groupe contrôle obtenu en pré-programme <span class="citation" data-cites="lakensCalculatingReportingEffect2013">(<a href="references.html#ref-lakensCalculatingReportingEffect2013" role="doc-biblioref">Lakens, 2013</a>)</span>.</p>
<p>Dans R, le <span class="math inline">\(\Delta\)</span> de Glass lié à un échantillon de population peut être calculé à l’aide de la fonction <code>glass_delta()</code> du package <code>{effectsize}</code>. Attention, l’écart-type utilisé dans le code suivant est celui de la variable quantitative associée à la modalité 2 de la variable qualitative, qui est toujours <code>versicolor</code> dans cet exemple (exemple dont le contexte n’est certes pas celui d’un programme dont on cherche l’effet, mais le principe d’utilisation du code reste le même).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>gd <span class="ot">&lt;-</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">glass_delta</span>(</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>    Sepal.Length <span class="sc">~</span> Species, </span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> iris_two_species</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>gd</span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Glass' delta (adj.) |         95% CI
------------------------------------
-1.77               | [-2.25, -1.29]</code></pre>
</div>
</div>
<p>Notons quand même que l’utilisation du <span class="math inline">\(\Delta\)</span> de Glass semble peu courante dans les études cherchant à tester l’effet d’un programme. L’une des difficultés liées à son utilisation est que cela suggère que les groupes à comparer soient identiques en pré-programme pour la variable étudiée. En général, des procédures un peu plus sophistiquées sont utilisées pour déterminer l’effet d’un programme, en particulier des procédures qui permettent de prendre en compte justement les différences qui peuvent exister entre les groupes en pré-programme.</p>
</section>
<section id="qualification-de-limportance-de-la-différence-de-moyennes-standardisée" class="level6" data-number="5.1.2.2.1.4">
<h6 data-number="5.1.2.2.1.4" class="anchored" data-anchor-id="qualification-de-limportance-de-la-différence-de-moyennes-standardisée"><span class="header-section-number">5.1.2.2.1.4</span> Qualification de l’importance de la différence de moyennes standardisée</h6>
<p>Une fois que l’on a calculé une taille d’effet, il est toujours intéressant d’essayer de formuler un jugement sur l’importance, l’ampleur de l’effet. En ce sens, des valeurs seuils ont été proposées dans la littérature pour les différences de moyennes standardisées (Cohen, 1988; in Lakens <span class="citation" data-cites="lakensCalculatingReportingEffect2013">(<a href="references.html#ref-lakensCalculatingReportingEffect2013" role="doc-biblioref">2013</a>)</span>). Ces valeurs, valables pour interpréter des tailles d’effet dans le cadre d’une étude de type <em>between-subject design</em>, sont montrées dans le <a href="#tbl-effectsizedtable" class="quarto-xref">Tableau&nbsp;<span>5.1</span></a> ci-dessous.</p>
<div class="cell">
<div id="tbl-effectsizedtable" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-effectsizedtable-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tableau&nbsp;5.1: Proposition de termes pour qualifier l’importance d’une différence de moyennes standardisée
</figcaption>
<div aria-describedby="tbl-effectsizedtable-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<div class="tabwid"><style>.cl-5fb4721c{}.cl-5fab92fa{font-family:'Arial';font-size:11pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-5fab930e{font-family:'Arial';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-5faece16{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-5faeed06{width:0.676in;background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1.5pt solid rgba(0, 0, 0, 1.00);border-top: 1.5pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-5faeed10{width:0.769in;background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1.5pt solid rgba(0, 0, 0, 1.00);border-top: 1.5pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-5faeed11{width:0.735in;background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1.5pt solid rgba(0, 0, 0, 1.00);border-top: 1.5pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-5faeed1a{width:0.676in;background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1.5pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-5faeed1b{width:0.769in;background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1.5pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-5faeed24{width:0.735in;background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1.5pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing="true" class="cl-5fb4721c"><thead><tr style="overflow-wrap:break-word;"><th class="cl-5faeed06"><p class="cl-5faece16"><span class="cl-5fab92fa">Petit</span></p></th><th class="cl-5faeed10"><p class="cl-5faece16"><span class="cl-5fab92fa">Moyen</span></p></th><th class="cl-5faeed11"><p class="cl-5faece16"><span class="cl-5fab92fa">Grand</span></p></th></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-5faeed1a"><p class="cl-5faece16"><span class="cl-5fab930e">&gt;=0.2</span></p></td><td class="cl-5faeed1b"><p class="cl-5faece16"><span class="cl-5fab930e">&gt;=0.5</span></p></td><td class="cl-5faeed24"><p class="cl-5faece16"><span class="cl-5fab930e">&gt;=0.8</span></p></td></tr></tbody></table></div>
</div>
</div>
</figure>
</div>
</div>
<p>Pour obtenir une interprétation automatique en même temps que la valeur de différence de moyennes standardisée, on peut utiliser les fonctions <code>interpret_cohens_d()</code>, <code>interpret_hedges_g()</code> et <code>interpret_glass_delta()</code> du package <code>{effectsize}</code> :</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">interpret_cohens_d</span>(ds)</span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Cohen's d |         95% CI | Interpretation
-------------------------------------------
-2.10     | [-2.59, -1.61] |          large

- Estimated using pooled SD.
- Interpretation rule: cohen1988</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">interpret_hedges_g</span>(gs)</span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Hedges' g |         95% CI | Interpretation
-------------------------------------------
-2.09     | [-2.57, -1.60] |          large

- Estimated using pooled SD.
- Interpretation rule: cohen1988</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">interpret_glass_delta</span>(gd[<span class="dv">1</span>, <span class="dv">1</span>])</span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "large"
(Rules: cohen1988)</code></pre>
</div>
</div>
</section>
</section>
<section id="dominance-1" class="level5" data-number="5.1.2.2.2">
<h5 data-number="5.1.2.2.2" class="anchored" data-anchor-id="dominance-1"><span class="header-section-number">5.1.2.2.2</span> Dominance</h5>
<p>La corrélation bisériale des rangs fournit une mesure de la notion de dominance d’un groupe par rapport à l’autre. Sa formule pour la comparaison de deux groupes non appariés est la suivante :</p>
<p><span class="math display">\[
\frac{\sum_{i=1}^{N} rank(X_{i}) - N_{X} (N_{X} + 1) / 2}{N_{X}  N_{Y}} - \frac{\sum_{i=1}^{N} rank(Y_{i}) - N_{Y} (N_{Y} + 1) / 2}{N_{X}  N_{Y}},
\]</span></p>
<p>avec <span class="math inline">\(rank(X_{i})\)</span> et <span class="math inline">\(rank(Y_{i})\)</span> les rangs des observations des variables <span class="math inline">\(X\)</span> et <span class="math inline">\(Y\)</span> toutes observations confondues, et <span class="math inline">\(N_{X}\)</span> et <span class="math inline">\(N_{Y}\)</span> les nombres d’observations pour les variables <span class="math inline">\(X\)</span> et <span class="math inline">\(Y\)</span> respectivement. Cette corrélation peut être obtenue manuellement dans R de la manière suivante :</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcul des rangs relatifs aux observations des deux modalités confondues</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>ranks <span class="ot">&lt;-</span> <span class="fu">rank</span>(iris_two_species<span class="sc">$</span>Sepal.Length)</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Obtention du nombre d'observations pour setosa et versicolor</span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>n_setosa <span class="ot">&lt;-</span> <span class="fu">nrow</span>(iris_two_species <span class="sc">|&gt;</span> <span class="fu">filter</span>(Species <span class="sc">==</span> <span class="st">"setosa"</span>))</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>n_versicolor <span class="ot">&lt;-</span> <span class="fu">nrow</span>(iris_two_species <span class="sc">|&gt;</span> <span class="fu">filter</span>(Species <span class="sc">==</span> <span class="st">"versicolor"</span>))</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcul de la somme des rangs normalisée pour l'espèce `setosa`</span></span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>sum_rks_setosa <span class="ot">&lt;-</span></span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>  (<span class="fu">sum</span>(ranks[<span class="fu">which</span>(iris_two_species<span class="sc">$</span>Species <span class="sc">==</span> <span class="st">"setosa"</span>)]) <span class="sc">-</span> n_setosa <span class="sc">*</span> (n_setosa <span class="sc">+</span> <span class="dv">1</span>) <span class="sc">/</span></span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a>     <span class="dv">2</span>) <span class="sc">/</span> (n_setosa <span class="sc">*</span> n_versicolor)</span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcul de la somme des rangs normalisée pour l'espèce `versicolor`</span></span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a>sum_rks_versicolor <span class="ot">&lt;-</span></span>
<span id="cb26-15"><a href="#cb26-15" aria-hidden="true" tabindex="-1"></a>  (<span class="fu">sum</span>(ranks[<span class="fu">which</span>(iris_two_species<span class="sc">$</span>Species <span class="sc">==</span> <span class="st">"versicolor"</span>)]) <span class="sc">-</span> n_versicolor <span class="sc">*</span> (n_versicolor <span class="sc">+</span> <span class="dv">1</span>) <span class="sc">/</span></span>
<span id="cb26-16"><a href="#cb26-16" aria-hidden="true" tabindex="-1"></a>     <span class="dv">2</span>) <span class="sc">/</span> (n_setosa <span class="sc">*</span> n_versicolor)</span>
<span id="cb26-17"><a href="#cb26-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-18"><a href="#cb26-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Obtention de la corrélation bisériale</span></span>
<span id="cb26-19"><a href="#cb26-19" aria-hidden="true" tabindex="-1"></a>janitor<span class="sc">::</span><span class="fu">round_half_up</span>(sum_rks_setosa <span class="sc">-</span> sum_rks_versicolor, <span class="dv">2</span>)</span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -0.87</code></pre>
</div>
</div>
<p>La corrélation bisériale des rangs peut s’obtenir facilement avec la fonction <code>rank_biserial()</code> du package <code>{effectsize}</code> comme ceci :</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>rb <span class="ot">&lt;-</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rank_biserial</span>(</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>    Sepal.Length <span class="sc">~</span> Species, </span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> iris_two_species, </span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">paired =</span> <span class="cn">FALSE</span></span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>rb</span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>r (rank biserial) |         95% CI
----------------------------------
-0.87             | [-0.91, -0.80]</code></pre>
</div>
</div>
<p>Le résultat indique que les observations liées à la seconde modalité de la variable <code>Species</code>, qui est <code>versicolor</code>, ont en général des valeurs supérieures à celles relatives à la modalité <code>setosa</code>.</p>
<p>La grandeur de la corrélation bisériale des rangs peut être caractérisée à l’aide de la classification de Funder &amp; Ozer (2019) proposée par défaut dans le package <code>{effectsize}</code> (<a href="#tbl-effectsizecorrb" class="quarto-xref">Tableau&nbsp;<span>5.2</span></a>) :</p>
<div class="cell">
<div id="tbl-effectsizecorrb" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-effectsizecorrb-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tableau&nbsp;5.2: Proposition de termes pour qualifier l’importance d’une corrélation bisériale des rangs
</figcaption>
<div aria-describedby="tbl-effectsizecorrb-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<div class="tabwid"><style>.cl-5ff16a50{}.cl-5fea65ca{font-family:'Arial';font-size:11pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-5fea65d4{font-family:'Arial';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-5fece4da{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-5fecfeac{width:1.058in;background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1.5pt solid rgba(0, 0, 0, 1.00);border-top: 1.5pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-5fecfeb6{width:0.701in;background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1.5pt solid rgba(0, 0, 0, 1.00);border-top: 1.5pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-5fecfeb7{width:0.947in;background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1.5pt solid rgba(0, 0, 0, 1.00);border-top: 1.5pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-5fecfec0{width:0.82in;background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1.5pt solid rgba(0, 0, 0, 1.00);border-top: 1.5pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-5fecfec1{width:1.16in;background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1.5pt solid rgba(0, 0, 0, 1.00);border-top: 1.5pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-5fecfeca{width:1.058in;background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1.5pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-5fecfecb{width:0.701in;background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1.5pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-5fecfed4{width:0.947in;background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1.5pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-5fecfed5{width:0.82in;background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1.5pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-5fecfed6{width:1.16in;background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1.5pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing="true" class="cl-5ff16a50"><thead><tr style="overflow-wrap:break-word;"><th class="cl-5fecfeac"><p class="cl-5fece4da"><span class="cl-5fea65ca">Très petite</span></p></th><th class="cl-5fecfeb6"><p class="cl-5fece4da"><span class="cl-5fea65ca">Petite</span></p></th><th class="cl-5fecfeb7"><p class="cl-5fece4da"><span class="cl-5fea65ca">Moyenne</span></p></th><th class="cl-5fecfec0"><p class="cl-5fece4da"><span class="cl-5fea65ca">Grande</span></p></th><th class="cl-5fecfec1"><p class="cl-5fece4da"><span class="cl-5fea65ca">Très grande</span></p></th></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-5fecfeca"><p class="cl-5fece4da"><span class="cl-5fea65d4">&gt;=0.05</span></p></td><td class="cl-5fecfecb"><p class="cl-5fece4da"><span class="cl-5fea65d4">&gt;=0.1</span></p></td><td class="cl-5fecfed4"><p class="cl-5fece4da"><span class="cl-5fea65d4">&gt;=0.2</span></p></td><td class="cl-5fecfed5"><p class="cl-5fece4da"><span class="cl-5fea65d4">&gt;=0.3</span></p></td><td class="cl-5fecfed6"><p class="cl-5fece4da"><span class="cl-5fea65d4">&gt;=0.4</span></p></td></tr></tbody></table></div>
</div>
</div>
</figure>
</div>
</div>
<p>Pour obtenir une interprétation automatique en même temps que la valeur de corrélation, on peut utiliser la fonction <code>interpret_rb()</code> du package {effectsize} :</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">interpret_rank_biserial</span>(rb)</span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>r (rank biserial) |         95% CI | Interpretation
---------------------------------------------------
-0.87             | [-0.91, -0.80] |     very large

- Interpretation rule: funder2019</code></pre>
</div>
</div>
</section>
<section id="langage-commun-1" class="level5" data-number="5.1.2.2.3">
<h5 data-number="5.1.2.2.3" class="anchored" data-anchor-id="langage-commun-1"><span class="header-section-number">5.1.2.2.3</span> Langage commun</h5>
<p>Pour comparer les groupes en utilisant la probabilité de supériorité, on peut utiliser la fonction <code>p_superiority()</code> du package <code>{effectsize}</code> comme ceci :</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">p_superiority</span>(</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  Sepal.Length <span class="sc">~</span> Species,</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> iris_two_species,</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">paired =</span> <span class="cn">FALSE</span>,</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">parametric =</span> <span class="cn">FALSE</span></span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Pr(superiority) |       95% CI
------------------------------
0.07            | [0.04, 0.10]

- Non-parametric CLES</code></pre>
</div>
</div>
<p>Le résultat indique que la probabilité d’avoir une valeur de <code>Sepal.Length</code> supérieure pour l’espèce <code>setosa</code> par rapport à l’espèce <code>versicolor</code> est de 7 % (réciproquement, la probabilité de supériorité pour l’espèce <code>setosa</code> est de 93 %). On note, dans le code ci-dessus, que l’argument <code>parametric</code> est configuré avec la valeur <code>FALSE</code>. Cela implique que l’estimation fournie est non paramétrique. De cette manière, la probabilité de supériorité est calculée à partir de la corrélation bisériale des rangs tel que : <span class="math inline">\(Pr(Superiority) = (r_{rb} + 1)/2\)</span>. Ce calcul serait le plus précis (le moins biaisé), notamment par rapport aux différences de moyennes standardisées classiques, sur un ensemble de scenarii de violation des conditions de normalité et d’hétérogénéité de variance <span class="citation" data-cites="liEffectSizeMeasures2016">(<a href="references.html#ref-liEffectSizeMeasures2016" role="doc-biblioref">Li, 2016</a>)</span>. Dans le cas où on utiliserait <code>parametric</code> = <code>TRUE</code>, alors la probabilité de supériorité serait calculée comme suit : <span class="math inline">\(Pr(superiority) = \phi(d/ \sqrt{2})\)</span>, avec <span class="math inline">\(d\)</span> pour le <span class="math inline">\(d_{s}\)</span> de Cohen.</p>
</section>
</section>
</section>
<section id="comparer-deux-groupes-appariés" class="level3" data-number="5.1.3">
<h3 data-number="5.1.3" class="anchored" data-anchor-id="comparer-deux-groupes-appariés"><span class="header-section-number">5.1.3</span> Comparer deux groupes appariés</h3>
<section id="étudier-graphiquement-la-comparaison-1" class="level4" data-number="5.1.3.1">
<h4 data-number="5.1.3.1" class="anchored" data-anchor-id="étudier-graphiquement-la-comparaison-1"><span class="header-section-number">5.1.3.1</span> Étudier graphiquement la comparaison</h4>
<p>La <a href="#fig-raindcloudplotsBivPaired1" class="quarto-xref">Figure&nbsp;<span>5.2</span></a> montre une proposition de graphique dans le cas de l’étude d’une comparaison de deux groupes de données appariés. Pour cela, nous avons installé le package <code>{PairedData}</code> et chargé le jeu de données associé, appelé <code>Blink</code>. Pour information, <code>Blink</code> contient des données de taux de clignotement des yeux obtenues chez 12 sujets et dans deux conditions différentes : une tâche où il fallait diriger un stylo selon une trajectoire rectiligne (modalité <code>Straight</code>), et une tâche où il fallait diriger un stylo selon une trajectoire présentant des oscillations (<code>Oscillating</code>). Ce jeu de données a été un peu transformé pour pouvoir passer à l’étape de la conception graphique, comme montré ci-dessous.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Charger le package</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(PairedData)</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Charger le jeu de données</span></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(Blink)</span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Configurer le jeu de données pour l'exemple avec données appariées</span></span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a>Blink2 <span class="ot">&lt;-</span></span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a>  Blink <span class="sc">|&gt;</span></span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(</span>
<span id="cb34-11"><a href="#cb34-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">cols =</span> <span class="fu">c</span>(Straight, Oscillating),</span>
<span id="cb34-12"><a href="#cb34-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">names_to =</span> <span class="st">"Condition"</span>, </span>
<span id="cb34-13"><a href="#cb34-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">values_to =</span> <span class="st">"Blink_rate"</span></span>
<span id="cb34-14"><a href="#cb34-14" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">|&gt;</span></span>
<span id="cb34-15"><a href="#cb34-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb34-16"><a href="#cb34-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">Condition =</span> <span class="fu">fct_relevel</span>(</span>
<span id="cb34-17"><a href="#cb34-17" aria-hidden="true" tabindex="-1"></a>      Condition, <span class="st">"Straight"</span>, <span class="st">"Oscillating"</span></span>
<span id="cb34-18"><a href="#cb34-18" aria-hidden="true" tabindex="-1"></a>      )</span>
<span id="cb34-19"><a href="#cb34-19" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb34-20"><a href="#cb34-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-21"><a href="#cb34-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualisation du jeu de données</span></span>
<span id="cb34-22"><a href="#cb34-22" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(Blink2)</span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
  Subject Condition   Blink_rate
  &lt;fct&gt;   &lt;fct&gt;            &lt;dbl&gt;
1 S01     Straight          24  
2 S01     Oscillating       15  
3 S02     Straight          19.5
4 S02     Oscillating        6.6
5 S03     Straight           8.2
6 S03     Oscillating        1.9</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Création du graphique</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> Blink2, <span class="fu">aes</span>(<span class="at">x =</span> Condition, <span class="at">y =</span> Blink_rate)) <span class="sc">+</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_rain</span>(</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">rain.side =</span> <span class="st">"f1x1"</span>,</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">id.long.var =</span> <span class="st">"Subject"</span>,</span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">point.args =</span> rlang<span class="sc">::</span><span class="fu">list2</span>(<span class="at">alpha =</span> <span class="fl">0.3</span>)</span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(</span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">group =</span> <span class="dv">1</span>),</span>
<span id="cb36-10"><a href="#cb36-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">fun =</span> <span class="st">"mean"</span>,</span>
<span id="cb36-11"><a href="#cb36-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">geom =</span> <span class="st">"line"</span>,</span>
<span id="cb36-12"><a href="#cb36-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">linewidth =</span> <span class="dv">1</span></span>
<span id="cb36-13"><a href="#cb36-13" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb36-14"><a href="#cb36-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(</span>
<span id="cb36-15"><a href="#cb36-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">geom =</span> <span class="st">"errorbar"</span>,</span>
<span id="cb36-16"><a href="#cb36-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">fun.data =</span> <span class="st">"mean_sdl"</span>,</span>
<span id="cb36-17"><a href="#cb36-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">fun.args =</span> <span class="fu">list</span>(<span class="at">mult =</span> <span class="dv">1</span>),</span>
<span id="cb36-18"><a href="#cb36-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">size =</span> <span class="fl">1.1</span>, </span>
<span id="cb36-19"><a href="#cb36-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">width =</span> <span class="fl">0.06</span></span>
<span id="cb36-20"><a href="#cb36-20" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">+</span> </span>
<span id="cb36-21"><a href="#cb36-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(</span>
<span id="cb36-22"><a href="#cb36-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">geom =</span> <span class="st">"point"</span>,</span>
<span id="cb36-23"><a href="#cb36-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">fun =</span> <span class="st">"mean"</span>, </span>
<span id="cb36-24"><a href="#cb36-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">size =</span> <span class="dv">3</span></span>
<span id="cb36-25"><a href="#cb36-25" aria-hidden="true" tabindex="-1"></a>    )</span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-raindcloudplotsBivPaired1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-raindcloudplotsBivPaired1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="two_group_comparison_files/figure-html/fig-raindcloudplotsBivPaired1-1.png" class="img-fluid figure-img" style="width:90.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-raindcloudplotsBivPaired1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.2: Exemple de graphique pour une comparaison de deux groupes de valeurs appariés (dépendants)
</figcaption>
</figure>
</div>
</div>
</div>
<p>Le graphique montré ci-dessus pour des données appariées contient des éléments graphiques supplémentaires par rapport à celui proposé pour les données non appariées : des lignes reliant les données individuelles, et une ligne reliant les statistiques qui représentent les tendances centrales (ici les moyennes). Ces deux types d’éléments graphiques sont importants pour explicitement montrer qu’il y a un lien entre les deux conditions de mesure (il s’agit des mêmes individus et donc du même groupe), et cela permet de mettre en évidence à la fois les trajectoires individuelles et celle du groupe entre les deux conditions de mesure.</p>
<p>Pour obtenir ces éléments supplémentaires, il a fallu configurer l’argument <code>id.long.var</code> de la fonction <code>geom_rain()</code> pour indiquer le nom de la variable sur laquelle se baser pour garder l’appariement des données individuelles entre les deux conditions et ainsi permettre un bon tracé des lignes individuelles. La ligne reliant les moyennes a été ajoutée grâce à la fonction<code>stat_summary()</code> avec la particularité d’indiquer <code>1</code> pour l’argument <code>group</code> de la fonction <code>aes()</code> associée à la fonction <code>stat_summary()</code>. Enfin, l’argument <code>rain.side</code> de la fonction <code>geom_rain()</code> a été configuré de telle sorte à avoir les données des deux groupes en vis-à-vis, mais un autre choix aurait pu être fait.</p>
</section>
<section id="étudier-numériquement-la-comparaison-1" class="level4" data-number="5.1.3.2">
<h4 data-number="5.1.3.2" class="anchored" data-anchor-id="étudier-numériquement-la-comparaison-1"><span class="header-section-number">5.1.3.2</span> Étudier numériquement la comparaison</h4>
<section id="différences-de-moyennes-standardisées-2" class="level5" data-number="5.1.3.2.1">
<h5 data-number="5.1.3.2.1" class="anchored" data-anchor-id="différences-de-moyennes-standardisées-2"><span class="header-section-number">5.1.3.2.1</span> Différences de moyennes standardisées</h5>
<section id="d_z-et-d_av-de-cohen" class="level6" data-number="5.1.3.2.1.1">
<h6 data-number="5.1.3.2.1.1" class="anchored" data-anchor-id="d_z-et-d_av-de-cohen"><span class="header-section-number">5.1.3.2.1.1</span> <span class="math inline">\(d_{z}\)</span> et <span class="math inline">\(d_{av}\)</span> de Cohen</h6>
<p>Le calcul classique pour obtenir la taille d’effet désignant l’écart de moyennes entre deux groupes de données dépendants est celui du <span class="math inline">\(d_{z}\)</span> <span class="citation" data-cites="lakensCalculatingReportingEffect2013">(<a href="references.html#ref-lakensCalculatingReportingEffect2013" role="doc-biblioref">Lakens, 2013</a>)</span>, qui est montré ci-dessous :</p>
<p><span class="math display">\[d_{z} = \frac{\overline{X} _{diff}}{\hat{\sigma}_{diff}},\]</span></p>
<p><span class="math inline">\(\overline{X}_{diff}\)</span> désignant la moyenne des différences relatives à chaque pair de valeurs obtenues dans les deux conditions comparées, et <span class="math inline">\(\hat{\sigma}_{diff}\)</span> désignant l’écart-type de ces différences.</p>
<p>Dans R, on peut calculer manuellement <span class="math inline">\(d_z\)</span> comme ceci (avec le jeu de données <code>Blink</code>) :</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcul des paramètres</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>diff <span class="ot">&lt;-</span> Blink<span class="sc">$</span>Straight <span class="sc">-</span> Blink<span class="sc">$</span>Oscillating</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>mean_diff <span class="ot">&lt;-</span> <span class="fu">mean</span>(diff)</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>sd_diff <span class="ot">&lt;-</span> <span class="fu">sd</span>(diff)</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcul de dz</span></span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>dz <span class="ot">&lt;-</span> mean_diff <span class="sc">/</span> sd_diff</span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a>dz</span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.811462</code></pre>
</div>
</div>
<p>Le <span class="math inline">\(d_{z}\)</span> peut être obtenu automatiquement avec la fonction <code>rm_d()</code> du package <code>{effectsize}</code>. Pour illustrer cela, nous allons utiliser le jeu de données <code>Blink2</code> crée plus haut pour l’exemple de graphique :</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>dz <span class="ot">&lt;-</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rm_d</span>(</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>    Blink_rate <span class="sc">~</span> Condition <span class="sc">|</span> Subject,</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> Blink2,</span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">method =</span> <span class="st">"z"</span>,</span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">adjust =</span> <span class="cn">FALSE</span></span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a>dz</span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>d (z) |       95% CI
--------------------
2.81  | [1.55, 4.07]</code></pre>
</div>
</div>
<p>Parce que la valeur de <span class="math inline">\(d_z\)</span> dépend de la corrélation entre les deux groupes de valeurs comparés, certains auteurs préfèrent rapporter un autre indice statistique qui n’a pas cette propriété et qui en ce sens pourrait être davantage comparable au <span class="math inline">\(d\)</span> de Cohen obtenu dans les études avec groupes indépendants. Parmi les candidats possibles, il y a notamment le <span class="math inline">\(d_{av}\)</span> de Cohen <span class="citation" data-cites="lakensCalculatingReportingEffect2013">(<a href="references.html#ref-lakensCalculatingReportingEffect2013" role="doc-biblioref">Lakens, 2013</a>)</span>, dont la formule est montrée ci-dessous :</p>
<p><span class="math display">\[d_{av} = \frac{\overline{X} _{diff}}{\sqrt{\frac{\hat{\sigma}_{1}^2 + \hat{\sigma}_{2}^2} {2}}}\]</span></p>
<p>Ce calcul reviendrait donc à diviser la moyenne des différences (qui est égale à la différence de moyennes) par l’écart-type moyen relatif aux deux groupes de données. Manuellement cela donnerait (avec <code>Blink2</code>) :</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcul des paramètres</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>X1 <span class="ot">&lt;-</span> Blink2 <span class="sc">|&gt;</span> <span class="fu">filter</span>(Condition <span class="sc">==</span> <span class="st">"Straight"</span>) <span class="sc">|&gt;</span> <span class="fu">pull</span>(Blink_rate) <span class="sc">|&gt;</span> <span class="fu">mean</span>()</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>X2 <span class="ot">&lt;-</span> Blink2 <span class="sc">|&gt;</span> <span class="fu">filter</span>(Condition <span class="sc">==</span> <span class="st">"Oscillating"</span>) <span class="sc">|&gt;</span> <span class="fu">pull</span>(Blink_rate) <span class="sc">|&gt;</span> <span class="fu">mean</span>()</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>SD1 <span class="ot">&lt;-</span> Blink2 <span class="sc">|&gt;</span> <span class="fu">filter</span>(Condition <span class="sc">==</span> <span class="st">"Straight"</span>) <span class="sc">|&gt;</span> <span class="fu">pull</span>(Blink_rate) <span class="sc">|&gt;</span> <span class="fu">sd</span>()</span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>SD2 <span class="ot">&lt;-</span> Blink2 <span class="sc">|&gt;</span> <span class="fu">filter</span>(Condition <span class="sc">==</span> <span class="st">"Oscillating"</span>) <span class="sc">|&gt;</span> <span class="fu">pull</span>(Blink_rate) <span class="sc">|&gt;</span> <span class="fu">sd</span>()</span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a>N1 <span class="ot">&lt;-</span> Blink2 <span class="sc">|&gt;</span> <span class="fu">filter</span>(Condition <span class="sc">==</span> <span class="st">"Straight"</span>) <span class="sc">|&gt;</span> <span class="fu">pull</span>(Blink_rate) <span class="sc">|&gt;</span> <span class="fu">length</span>()</span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a>N2 <span class="ot">&lt;-</span> Blink2 <span class="sc">|&gt;</span> <span class="fu">filter</span>(Condition <span class="sc">==</span> <span class="st">"Oscillating"</span>) <span class="sc">|&gt;</span> <span class="fu">pull</span>(Blink_rate) <span class="sc">|&gt;</span> <span class="fu">length</span>()</span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-9"><a href="#cb41-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcul de dav</span></span>
<span id="cb41-10"><a href="#cb41-10" aria-hidden="true" tabindex="-1"></a>dav <span class="ot">&lt;-</span> (X1 <span class="sc">-</span> X2) <span class="sc">/</span> <span class="fu">sqrt</span>((SD1<span class="sc">^</span><span class="dv">2</span> <span class="sc">+</span> SD2<span class="sc">^</span><span class="dv">2</span>) <span class="sc">/</span> <span class="dv">2</span>)</span>
<span id="cb41-11"><a href="#cb41-11" aria-hidden="true" tabindex="-1"></a>dav</span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.525146</code></pre>
</div>
</div>
<p>Le <span class="math inline">\(d_{av}\)</span> pour données appariées peut être obtenu automatiquement avec la fonction <code>rm_d()</code> du package <code>{effectsize}</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>dav <span class="ot">&lt;-</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rm_d</span>(</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>    Blink_rate <span class="sc">~</span> Condition <span class="sc">|</span> Subject,</span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> Blink2,</span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">method =</span> <span class="st">"av"</span>,</span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">adjust =</span> <span class="cn">FALSE</span></span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb43-8"><a href="#cb43-8" aria-hidden="true" tabindex="-1"></a>dav</span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>d (av) |       95% CI
---------------------
1.53   | [1.22, 1.83]</code></pre>
</div>
</div>
</section>
<section id="g_z-et-g_av-de-hedges" class="level6" data-number="5.1.3.2.1.2">
<h6 data-number="5.1.3.2.1.2" class="anchored" data-anchor-id="g_z-et-g_av-de-hedges"><span class="header-section-number">5.1.3.2.1.2</span> <span class="math inline">\(g_{z}\)</span> et <span class="math inline">\(g_{av}\)</span> de Hedges</h6>
<p>Comme pour les <span class="math inline">\(d\)</span> de Cohen calculés dans le cadre de groupes non appariés, les <span class="math inline">\(d\)</span> de Cohen obtenus avec groupes appariés sont positivement biaisés. À nouveau, ces indices statistiques peuvent être corrigés avec le même facteur de correction montré pour le <span class="math inline">\(g\)</span> de Hedges dans la partie sur les groupes non appariés Toutefois, <span class="math inline">\(g_{av}\)</span> ne serait malgré tout pas complètement non biaisé <span class="citation" data-cites="lakensCalculatingReportingEffect2013">(<a href="references.html#ref-lakensCalculatingReportingEffect2013" role="doc-biblioref">Lakens, 2013</a>)</span>.</p>
<p>Pour obtenir <span class="math inline">\(g_z\)</span> :</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>gz <span class="ot">&lt;-</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rm_d</span>(</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>    Blink_rate <span class="sc">~</span> Condition <span class="sc">|</span> Subject,</span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> Blink2,</span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">method =</span> <span class="st">"z"</span>,</span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">adjust =</span> <span class="cn">TRUE</span></span>
<span id="cb45-7"><a href="#cb45-7" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb45-8"><a href="#cb45-8" aria-hidden="true" tabindex="-1"></a>gz</span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>d (z) |       95% CI
--------------------
2.61  | [1.44, 3.79]

- Adjusted for small sample bias.</code></pre>
</div>
</div>
<p>Pour obtenir <span class="math inline">\(g_{av}\)</span> :</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>gav <span class="ot">&lt;-</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rm_d</span>(</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>    Blink_rate <span class="sc">~</span> Condition <span class="sc">|</span> Subject,</span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> Blink2,</span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">method =</span> <span class="st">"av"</span>,</span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">adjust =</span> <span class="cn">TRUE</span></span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb47-8"><a href="#cb47-8" aria-hidden="true" tabindex="-1"></a>gav</span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>d (av) |       95% CI
---------------------
1.42   | [1.13, 1.70]

- Adjusted for small sample bias.</code></pre>
</div>
</div>
<p>Pour obtenir une interprétation des valeurs, on peut reprendre les procédures décrites pour les cas de groupes non appariés.</p>
</section>
</section>
<section id="dominance-2" class="level5" data-number="5.1.3.2.2">
<h5 data-number="5.1.3.2.2" class="anchored" data-anchor-id="dominance-2"><span class="header-section-number">5.1.3.2.2</span> Dominance</h5>
<p>Comme dans le cas de données non appariées, la corrélation bisériale des rangs peut être utilisée pour fournir une mesure de la notion de dominance d’une condition par rapport à une autre. Sa formule pour la comparaison de deux groupes appariés est la suivante :</p>
<p><span class="math display">\[
\frac{\sum_{i=1}^{N} (SignedRank(X_{i} - Y_{i}) &gt; 0)}{N (N+1) / 2} - \frac{\sum_{i=1}^{N} (SignedRank(X_{i} - Y_{i}) &lt; 0)}{N (N+1) / 2}(-1),
\]</span></p>
<p>avec <span class="math inline">\(SignedRank(X_{i} - Y_{i}))\)</span> les rangs signés associés aux observations des modalités <span class="math inline">\(X\)</span> et <span class="math inline">\(Y\)</span> toutes observations confondues, et <span class="math inline">\(N\)</span> le nombre d’individus étudiés. Cette corrélation peut être obtenue manuellement dans R de la manière suivante :</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Exemple avec le jeu de données `Blink2` crée plus haut</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="co"># On cherche à comparer les condition `Straight`et `Oscillating` pour la variable `Condition` </span></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(Blink2)</span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
  Subject Condition   Blink_rate
  &lt;fct&gt;   &lt;fct&gt;            &lt;dbl&gt;
1 S01     Straight          24  
2 S01     Oscillating       15  
3 S02     Straight          19.5
4 S02     Oscillating        6.6
5 S03     Straight           8.2
6 S03     Oscillating        1.9</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcul des différences entre les modalités</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>diffs <span class="ot">&lt;-</span> Blink2[Blink2<span class="sc">$</span>Condition <span class="sc">==</span> <span class="st">"Straight"</span>, <span class="st">"Blink_rate"</span>] <span class="sc">-</span> Blink2[Blink2<span class="sc">$</span>Condition <span class="sc">==</span> <span class="st">"Oscillating"</span>, <span class="st">"Blink_rate"</span>]</span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcul des rangs signés relatifs aux observations des deux modalités confondues</span></span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a>ranks <span class="ot">&lt;-</span> datawizard<span class="sc">::</span><span class="fu">ranktransform</span>(diffs, <span class="at">sign =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span> <span class="fu">pull</span>(Blink_rate)</span>
<span id="cb51-6"><a href="#cb51-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-7"><a href="#cb51-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Obtention du nombre d'individus</span></span>
<span id="cb51-8"><a href="#cb51-8" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">nrow</span>(Blink2 <span class="sc">|&gt;</span> <span class="fu">filter</span>(Condition <span class="sc">==</span> <span class="st">"Straight"</span>))</span>
<span id="cb51-9"><a href="#cb51-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-10"><a href="#cb51-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcul de la somme des rangs positifs normalisée</span></span>
<span id="cb51-11"><a href="#cb51-11" aria-hidden="true" tabindex="-1"></a>sum_rks_pos <span class="ot">&lt;-</span> <span class="fu">sum</span>(ranks[ranks <span class="sc">&gt;</span> <span class="dv">0</span>]) <span class="sc">/</span> (n <span class="sc">*</span> (n <span class="sc">+</span> <span class="dv">1</span>) <span class="sc">/</span> <span class="dv">2</span>)</span>
<span id="cb51-12"><a href="#cb51-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-13"><a href="#cb51-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcul de la somme des rangs négatifs normalisée</span></span>
<span id="cb51-14"><a href="#cb51-14" aria-hidden="true" tabindex="-1"></a>sum_rks_neg <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fu">sum</span>(ranks[ranks <span class="sc">&lt;</span> <span class="dv">0</span>]) <span class="sc">/</span> (n <span class="sc">*</span> (n <span class="sc">+</span> <span class="dv">1</span>) <span class="sc">/</span> <span class="dv">2</span>)</span>
<span id="cb51-15"><a href="#cb51-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-16"><a href="#cb51-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Obtention de la corrélation bisériale</span></span>
<span id="cb51-17"><a href="#cb51-17" aria-hidden="true" tabindex="-1"></a>janitor<span class="sc">::</span><span class="fu">round_half_up</span>(sum_rks_pos <span class="sc">-</span> sum_rks_neg, <span class="dv">2</span>)</span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1</code></pre>
</div>
</div>
<p>La corrélation bisériale des rangs peut s’obtenir facilement avec la fonction <code>rank_biserial()</code> du package <code>{effectsize}</code> comme ceci :</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>rb <span class="ot">&lt;-</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rank_biserial</span>(</span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>  Blink2 <span class="sc">|&gt;</span> <span class="fu">filter</span>(Condition <span class="sc">==</span> <span class="st">"Straight"</span>) <span class="sc">|&gt;</span> <span class="fu">pull</span>(Blink_rate),</span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a>  Blink2 <span class="sc">|&gt;</span> <span class="fu">filter</span>(Condition <span class="sc">==</span> <span class="st">"Oscillating"</span>) <span class="sc">|&gt;</span> <span class="fu">pull</span>(Blink_rate),</span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> Blink2,</span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">paired =</span> <span class="cn">TRUE</span></span>
<span id="cb53-7"><a href="#cb53-7" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb53-8"><a href="#cb53-8" aria-hidden="true" tabindex="-1"></a>rb</span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>r (rank biserial) |       95% CI
--------------------------------
1.00              | [1.00, 1.00]</code></pre>
</div>
</div>
<p>Le résultat indique que les observations liées à la deuxième modalité de la variable <code>Condition</code>, qui est <code>Oscillating</code>, ont systématiquement des valeurs inférieures à celles relatives à la modalité <code>Straight</code> (pour un même individu).</p>
<p>Pour obtenir une interprétation des valeurs, on peut reprendre les procédures décrites pour les cas de groupes non appariés.</p>
</section>
<section id="langage-commun-2" class="level5" data-number="5.1.3.2.3">
<h5 data-number="5.1.3.2.3" class="anchored" data-anchor-id="langage-commun-2"><span class="header-section-number">5.1.3.2.3</span> Langage commun</h5>
<p>Pour comparer les groupes en utilisant la probabilité de supériorité, on peut à nouveau utiliser la fonction <code>p_superiority()</code> du package <code>{effectsize}</code> comme ceci :</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">p_superiority</span>(</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>  Blink2 <span class="sc">|&gt;</span> <span class="fu">filter</span>(Condition <span class="sc">==</span> <span class="st">"Straight"</span>) <span class="sc">|&gt;</span> <span class="fu">pull</span>(Blink_rate),</span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>  Blink2 <span class="sc">|&gt;</span> <span class="fu">filter</span>(Condition <span class="sc">==</span> <span class="st">"Oscillating"</span>) <span class="sc">|&gt;</span> <span class="fu">pull</span>(Blink_rate),</span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">paired =</span> <span class="cn">TRUE</span>,</span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">parametric =</span> <span class="cn">FALSE</span></span>
<span id="cb55-6"><a href="#cb55-6" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Pr(superiority) |       95% CI
------------------------------
1.00            | [1.00, 1.00]

- Non-parametric CLES</code></pre>
</div>
</div>
<p>Le résultat indique que la probabilité d’avoir une valeur de <code>Blink_rate</code> supérieure pour la condition <code>Oscillating</code> par rapport à la condition <code>Straight</code> est de 100 % (réciproquement, la probabilité de supériorité pour la condition <code>Straight</code> est de 0 %).</p>
</section>
</section>
</section>
</section>
<section id="comparaison-sur-une-variable-qualitative" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="comparaison-sur-une-variable-qualitative"><span class="header-section-number">5.2</span> Comparaison sur une variable qualitative</h2>
<p>Pour cette partie, on s’appuie sur le jeu de données qui a permis par le passé l’étude comparative des taux de réussite des femmes et des hommes à l’Université de Berkeley en 1973 <span class="citation" data-cites="bickelSexBiasGraduate1975">(<a href="references.html#ref-bickelSexBiasGraduate1975" role="doc-biblioref">Bickel et al., 1975</a>)</span>. Un aperçu du jeu de données est montré ci-dessous :</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Créer variable Département</span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>department <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">rep</span>(<span class="st">"A"</span>, <span class="dv">4</span>),</span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>                <span class="fu">rep</span>(<span class="st">"B"</span>, <span class="dv">4</span>),</span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a>                <span class="fu">rep</span>(<span class="st">"C"</span>, <span class="dv">4</span>),</span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a>                <span class="fu">rep</span>(<span class="st">"D"</span>, <span class="dv">4</span>),</span>
<span id="cb57-6"><a href="#cb57-6" aria-hidden="true" tabindex="-1"></a>                <span class="fu">rep</span>(<span class="st">"E"</span>, <span class="dv">4</span>),</span>
<span id="cb57-7"><a href="#cb57-7" aria-hidden="true" tabindex="-1"></a>                <span class="fu">rep</span>(<span class="st">"F"</span>, <span class="dv">4</span>))</span>
<span id="cb57-8"><a href="#cb57-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-9"><a href="#cb57-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Créer variable Résultat</span></span>
<span id="cb57-10"><a href="#cb57-10" aria-hidden="true" tabindex="-1"></a>result <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb57-11"><a href="#cb57-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rep</span>(<span class="st">"Admitted"</span>, <span class="dv">2</span>),</span>
<span id="cb57-12"><a href="#cb57-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rep</span>(<span class="st">"Rejected"</span>, <span class="dv">2</span>),</span>
<span id="cb57-13"><a href="#cb57-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rep</span>(<span class="st">"Admitted"</span>, <span class="dv">2</span>),</span>
<span id="cb57-14"><a href="#cb57-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rep</span>(<span class="st">"Rejected"</span>, <span class="dv">2</span>),</span>
<span id="cb57-15"><a href="#cb57-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rep</span>(<span class="st">"Admitted"</span>, <span class="dv">2</span>),</span>
<span id="cb57-16"><a href="#cb57-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rep</span>(<span class="st">"Rejected"</span>, <span class="dv">2</span>),</span>
<span id="cb57-17"><a href="#cb57-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rep</span>(<span class="st">"Admitted"</span>, <span class="dv">2</span>),</span>
<span id="cb57-18"><a href="#cb57-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rep</span>(<span class="st">"Rejected"</span>, <span class="dv">2</span>),</span>
<span id="cb57-19"><a href="#cb57-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rep</span>(<span class="st">"Admitted"</span>, <span class="dv">2</span>),</span>
<span id="cb57-20"><a href="#cb57-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rep</span>(<span class="st">"Rejected"</span>, <span class="dv">2</span>),</span>
<span id="cb57-21"><a href="#cb57-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rep</span>(<span class="st">"Admitted"</span>, <span class="dv">2</span>),</span>
<span id="cb57-22"><a href="#cb57-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rep</span>(<span class="st">"Rejected"</span>, <span class="dv">2</span>)</span>
<span id="cb57-23"><a href="#cb57-23" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb57-24"><a href="#cb57-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-25"><a href="#cb57-25" aria-hidden="true" tabindex="-1"></a><span class="co"># Créer variable Sexe</span></span>
<span id="cb57-26"><a href="#cb57-26" aria-hidden="true" tabindex="-1"></a>sex <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb57-27"><a href="#cb57-27" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Male"</span>,</span>
<span id="cb57-28"><a href="#cb57-28" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Female"</span>,</span>
<span id="cb57-29"><a href="#cb57-29" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Male"</span>,</span>
<span id="cb57-30"><a href="#cb57-30" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Female"</span>,</span>
<span id="cb57-31"><a href="#cb57-31" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Male"</span>,</span>
<span id="cb57-32"><a href="#cb57-32" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Female"</span>,</span>
<span id="cb57-33"><a href="#cb57-33" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Male"</span>,</span>
<span id="cb57-34"><a href="#cb57-34" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Female"</span>,</span>
<span id="cb57-35"><a href="#cb57-35" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Male"</span>,</span>
<span id="cb57-36"><a href="#cb57-36" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Female"</span>,</span>
<span id="cb57-37"><a href="#cb57-37" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Male"</span>,</span>
<span id="cb57-38"><a href="#cb57-38" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Female"</span>,</span>
<span id="cb57-39"><a href="#cb57-39" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Male"</span>,</span>
<span id="cb57-40"><a href="#cb57-40" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Female"</span>,</span>
<span id="cb57-41"><a href="#cb57-41" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Male"</span>,</span>
<span id="cb57-42"><a href="#cb57-42" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Female"</span>,</span>
<span id="cb57-43"><a href="#cb57-43" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Male"</span>,</span>
<span id="cb57-44"><a href="#cb57-44" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Female"</span>,</span>
<span id="cb57-45"><a href="#cb57-45" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Male"</span>,</span>
<span id="cb57-46"><a href="#cb57-46" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Female"</span>,</span>
<span id="cb57-47"><a href="#cb57-47" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Male"</span>,</span>
<span id="cb57-48"><a href="#cb57-48" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Female"</span>,</span>
<span id="cb57-49"><a href="#cb57-49" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Male"</span>,</span>
<span id="cb57-50"><a href="#cb57-50" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Female"</span></span>
<span id="cb57-51"><a href="#cb57-51" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb57-52"><a href="#cb57-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-53"><a href="#cb57-53" aria-hidden="true" tabindex="-1"></a><span class="co"># Effectifs</span></span>
<span id="cb57-54"><a href="#cb57-54" aria-hidden="true" tabindex="-1"></a>effectif <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb57-55"><a href="#cb57-55" aria-hidden="true" tabindex="-1"></a>  <span class="dv">512</span>,</span>
<span id="cb57-56"><a href="#cb57-56" aria-hidden="true" tabindex="-1"></a>  <span class="dv">89</span>,</span>
<span id="cb57-57"><a href="#cb57-57" aria-hidden="true" tabindex="-1"></a>  <span class="dv">313</span>,</span>
<span id="cb57-58"><a href="#cb57-58" aria-hidden="true" tabindex="-1"></a>  <span class="dv">19</span>,</span>
<span id="cb57-59"><a href="#cb57-59" aria-hidden="true" tabindex="-1"></a>  <span class="dv">353</span>,</span>
<span id="cb57-60"><a href="#cb57-60" aria-hidden="true" tabindex="-1"></a>  <span class="dv">17</span>,</span>
<span id="cb57-61"><a href="#cb57-61" aria-hidden="true" tabindex="-1"></a>  <span class="dv">207</span>,</span>
<span id="cb57-62"><a href="#cb57-62" aria-hidden="true" tabindex="-1"></a>  <span class="dv">8</span>,</span>
<span id="cb57-63"><a href="#cb57-63" aria-hidden="true" tabindex="-1"></a>  <span class="dv">120</span>,</span>
<span id="cb57-64"><a href="#cb57-64" aria-hidden="true" tabindex="-1"></a>  <span class="dv">202</span>,</span>
<span id="cb57-65"><a href="#cb57-65" aria-hidden="true" tabindex="-1"></a>  <span class="dv">205</span>,</span>
<span id="cb57-66"><a href="#cb57-66" aria-hidden="true" tabindex="-1"></a>  <span class="dv">391</span>,</span>
<span id="cb57-67"><a href="#cb57-67" aria-hidden="true" tabindex="-1"></a>  <span class="dv">138</span>,</span>
<span id="cb57-68"><a href="#cb57-68" aria-hidden="true" tabindex="-1"></a>  <span class="dv">131</span>,</span>
<span id="cb57-69"><a href="#cb57-69" aria-hidden="true" tabindex="-1"></a>  <span class="dv">279</span>,</span>
<span id="cb57-70"><a href="#cb57-70" aria-hidden="true" tabindex="-1"></a>  <span class="dv">244</span>,</span>
<span id="cb57-71"><a href="#cb57-71" aria-hidden="true" tabindex="-1"></a>  <span class="dv">53</span>,</span>
<span id="cb57-72"><a href="#cb57-72" aria-hidden="true" tabindex="-1"></a>  <span class="dv">94</span>,</span>
<span id="cb57-73"><a href="#cb57-73" aria-hidden="true" tabindex="-1"></a>  <span class="dv">138</span>,</span>
<span id="cb57-74"><a href="#cb57-74" aria-hidden="true" tabindex="-1"></a>  <span class="dv">299</span>,</span>
<span id="cb57-75"><a href="#cb57-75" aria-hidden="true" tabindex="-1"></a>  <span class="dv">22</span>,</span>
<span id="cb57-76"><a href="#cb57-76" aria-hidden="true" tabindex="-1"></a>  <span class="dv">24</span>,</span>
<span id="cb57-77"><a href="#cb57-77" aria-hidden="true" tabindex="-1"></a>  <span class="dv">351</span>,</span>
<span id="cb57-78"><a href="#cb57-78" aria-hidden="true" tabindex="-1"></a>  <span class="dv">317</span></span>
<span id="cb57-79"><a href="#cb57-79" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb57-80"><a href="#cb57-80" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-81"><a href="#cb57-81" aria-hidden="true" tabindex="-1"></a><span class="co"># Créer data frame</span></span>
<span id="cb57-82"><a href="#cb57-82" aria-hidden="true" tabindex="-1"></a>res <span class="ot">&lt;-</span></span>
<span id="cb57-83"><a href="#cb57-83" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(</span>
<span id="cb57-84"><a href="#cb57-84" aria-hidden="true" tabindex="-1"></a>    <span class="at">department =</span> department,</span>
<span id="cb57-85"><a href="#cb57-85" aria-hidden="true" tabindex="-1"></a>    <span class="at">result =</span> result,</span>
<span id="cb57-86"><a href="#cb57-86" aria-hidden="true" tabindex="-1"></a>    <span class="at">sex =</span> sex,</span>
<span id="cb57-87"><a href="#cb57-87" aria-hidden="true" tabindex="-1"></a>    <span class="at">effectif =</span> effectif</span>
<span id="cb57-88"><a href="#cb57-88" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span> </span>
<span id="cb57-89"><a href="#cb57-89" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lapply</span>(rep, effectif) <span class="sc">|&gt;</span> </span>
<span id="cb57-90"><a href="#cb57-90" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>() <span class="sc">|&gt;</span> </span>
<span id="cb57-91"><a href="#cb57-91" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb57-92"><a href="#cb57-92" aria-hidden="true" tabindex="-1"></a>    <span class="at">id =</span> <span class="fu">seq_along</span>(sex),</span>
<span id="cb57-93"><a href="#cb57-93" aria-hidden="true" tabindex="-1"></a>    <span class="at">sex =</span> <span class="fu">fct_recode</span>(sex, <span class="st">"Femmes"</span> <span class="ot">=</span> <span class="st">"Female"</span>, <span class="st">"Hommes"</span> <span class="ot">=</span> <span class="st">"Male"</span>),</span>
<span id="cb57-94"><a href="#cb57-94" aria-hidden="true" tabindex="-1"></a>    <span class="at">result =</span> <span class="fu">fct_recode</span>(result, <span class="st">"Admis"</span> <span class="ot">=</span> <span class="st">"Admitted"</span>, <span class="st">"Refusé"</span> <span class="ot">=</span> <span class="st">"Rejected"</span>)</span>
<span id="cb57-95"><a href="#cb57-95" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">|&gt;</span> </span>
<span id="cb57-96"><a href="#cb57-96" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(id, sex, department, result)</span>
<span id="cb57-97"><a href="#cb57-97" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-98"><a href="#cb57-98" aria-hidden="true" tabindex="-1"></a><span class="co"># Aperçu du jeu de données</span></span>
<span id="cb57-99"><a href="#cb57-99" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(res)</span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  id    sex department result
1  1 Hommes          A  Admis
2  2 Hommes          A  Admis
3  3 Hommes          A  Admis
4  4 Hommes          A  Admis
5  5 Hommes          A  Admis
6  6 Hommes          A  Admis</code></pre>
</div>
</div>
<section id="étudier-graphiquement-la-comparaison-2" class="level3" data-number="5.2.1">
<h3 data-number="5.2.1" class="anchored" data-anchor-id="étudier-graphiquement-la-comparaison-2"><span class="header-section-number">5.2.1</span> Étudier graphiquement la comparaison</h3>
<p>On s’intéresse donc à la comparaison du taux de réussite des femmes et des hommes sur l’ensemble de l’Université de Berkeley. Un graphique qui peut être fait pour cette étude est le suivant :</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Créer le jeu de données</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>res_by_sex <span class="ot">&lt;-</span></span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>  res <span class="sc">|&gt;</span> </span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(sex, result) <span class="sc">|&gt;</span> </span>
<span id="cb59-5"><a href="#cb59-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(sex) <span class="sc">|&gt;</span> </span>
<span id="cb59-6"><a href="#cb59-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">prop =</span> janitor<span class="sc">::</span><span class="fu">round_half_up</span>(n <span class="sc">/</span> <span class="fu">sum</span>(n) <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">1</span>)) </span>
<span id="cb59-7"><a href="#cb59-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-8"><a href="#cb59-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Créer le graphique</span></span>
<span id="cb59-9"><a href="#cb59-9" aria-hidden="true" tabindex="-1"></a>res_by_sex <span class="sc">|&gt;</span> </span>
<span id="cb59-10"><a href="#cb59-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(result <span class="sc">==</span> <span class="st">"Admis"</span>) <span class="sc">|&gt;</span> </span>
<span id="cb59-11"><a href="#cb59-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> result, <span class="at">y =</span> prop, <span class="at">fill =</span> sex)) <span class="sc">+</span></span>
<span id="cb59-12"><a href="#cb59-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">position =</span> <span class="st">"dodge"</span>) <span class="sc">+</span></span>
<span id="cb59-13"><a href="#cb59-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">y =</span> prop <span class="sc">/</span> <span class="dv">2</span>, <span class="at">label =</span> <span class="fu">paste0</span>(prop, <span class="st">" %"</span>)), <span class="at">position =</span> <span class="fu">position_dodge</span>(.<span class="dv">9</span>)) <span class="sc">+</span></span>
<span id="cb59-14"><a href="#cb59-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span><span class="fu">label_percent</span>(<span class="at">scale =</span> <span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb59-15"><a href="#cb59-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Résultat"</span>, <span class="at">y =</span> <span class="st">"Taux de réussite (%)"</span>, <span class="at">fill =</span> <span class="st">"Sexe"</span>)</span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-taballUCBA" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-taballUCBA-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="two_group_comparison_files/figure-html/fig-taballUCBA-1.png" class="img-fluid figure-img" style="width:90.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-taballUCBA-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.3: Taux de réussite des étudiants femmes et hommes à l’Université de Berkeley en 1973, approche globale (Bickel et al., 1975)
</figcaption>
</figure>
</div>
</div>
</div>
<p>On voit ainsi qu’à l’échelle de l’Université, le taux de réussite des femmes était inférieur à celui des hommes. Toutefois, une analyse par département permettait de voir que les taux de réussite des femmes étaient en réalité supérieurs voire nettement supérieurs à ceux des hommes dans la plupart des départements (cf. <a href="#fig-tabdepUCBA" class="quarto-xref">Figure&nbsp;<span>5.4</span></a>).</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-tabdepUCBA" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-tabdepUCBA-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="two_group_comparison_files/figure-html/fig-tabdepUCBA-1.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-tabdepUCBA-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.4: Taux de réussite des étudiants femmes et hommes à l’Université de Berkeley en 1973, approche par département (Bickel et al., 1975)
</figcaption>
</figure>
</div>
</div>
</div>
<p>Cette situation, qui peut paraître étonnante, illustre ce qu’on appelle un paradoxe de Simpson. Dans le cas présent, l’apparent paradoxe s’explique par le fait que les femmes avaient en proportion davantage candidaté que les hommes dans des départements où le taux de réussite global était moins bon. Ceci est illustré sur la <a href="#fig-distriUCBA" class="quarto-xref">Figure&nbsp;<span>5.5</span></a>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-distriUCBA" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-distriUCBA-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="two_group_comparison_files/figure-html/fig-distriUCBA-1.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-distriUCBA-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.5: Mise en avant du département d’inscription comme facteur confondant dans l’étude du lien entre le sexe et le taux de réussite à l’Université de Berkeley en 1973 (Bickel et al., 1975)
</figcaption>
</figure>
</div>
</div>
</div>
<p>Autrement dit, les hommes avaient un taux de réussite global bien meilleur que celui des femmes parce que, comparativement aux femmes, les hommes s’étaient en proportion davantage engagés dans les départements où les taux de réussite étaient bien meilleurs.</p>
</section>
<section id="étudier-numériquement-la-comparaison-2" class="level3" data-number="5.2.2">
<h3 data-number="5.2.2" class="anchored" data-anchor-id="étudier-numériquement-la-comparaison-2"><span class="header-section-number">5.2.2</span> Étudier numériquement la comparaison</h3>
<section id="différence-de-risque" class="level4" data-number="5.2.2.1">
<h4 data-number="5.2.2.1" class="anchored" data-anchor-id="différence-de-risque"><span class="header-section-number">5.2.2.1</span> Différence de risque</h4>
<p>La différence de risque est une différence de proportions. La notion de risque peut ne pas être très pertinente pour certains contextes, comme le cas présenté ci-avant, mais elle l’est particulièrement dans un contexte de santé. Pour comprendre le calcul du risque puis de la différence de risque, regardons le tableau ci-dessous appliqué à l’exemple de notre étude sur la réussite à l’Université de Berkeley (<a href="#fig-RiskContTables" class="quarto-xref">Figure&nbsp;<span>5.6</span></a>).</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-RiskContTables" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-RiskContTables-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="two_group_comparison_files/figure-html/fig-RiskContTables-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-RiskContTables-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.6: Tableau de contingence schématique pour comprendre le calcul des risques et des cotes
</figcaption>
</figure>
</div>
</div>
</div>
<p>Dans le tableau ci-dessus, chaque case contenant un « n » est un effectif. Si l’on désire connaître le risque (ou plutôt la chance ici) d’être admis dans le groupe des femmes (<span class="math inline">\(p_{H/Adm}\)</span>) et dans le groupe des hommes (<span class="math inline">\(p_{F/Adm}\)</span>), on fait les calculs suivants :</p>
<p><span class="math display">\[p_{H/Adm} = \frac{n_{1}}{n_{1} + n_{3}}\]</span></p>
<p><span class="math display">\[p_{F/Adm} = \frac{n_{n2}}{n_{2} + n_{4}}\]</span></p>
<p>La différence de risque (ou plutôt de chance ici) d’être admis pour les femmes par rapport aux hommes, notée <span class="math inline">\(DR\)</span>, est alors :</p>
<p><span class="math display">\[DR = p_{H/Adm} - p_{F/Adm} \]</span> Manuellement, dans R, on aurait donc :</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Réarangement des niveaux de sexe</span></span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>res<span class="sc">$</span>sex <span class="ot">&lt;-</span> <span class="fu">factor</span>(res<span class="sc">$</span>sex, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Hommes"</span>, <span class="st">"Femmes"</span>))</span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Création du tableau de contingence</span></span>
<span id="cb60-5"><a href="#cb60-5" aria-hidden="true" tabindex="-1"></a>tab <span class="ot">&lt;-</span> <span class="fu">with</span>(res, <span class="fu">table</span>(result, sex))</span>
<span id="cb60-6"><a href="#cb60-6" aria-hidden="true" tabindex="-1"></a>tab</span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>        sex
result   Hommes Femmes
  Admis    1198    557
  Refusé   1493   1278</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Obtention de p(H/Adm)</span></span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>p_H_Adm <span class="ot">&lt;-</span> <span class="dv">1198</span> <span class="sc">/</span> (<span class="dv">1198</span> <span class="sc">+</span> <span class="dv">1493</span>) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a>p_H_Adm</span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 44.51877</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Obtention de p(F/Adm)</span></span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>p_F_Adm <span class="ot">&lt;-</span> <span class="dv">557</span> <span class="sc">/</span> (<span class="dv">557</span> <span class="sc">+</span> <span class="dv">1278</span>) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a>p_F_Adm</span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 30.35422</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcul de la différence de risque</span></span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a>janitor<span class="sc">::</span><span class="fu">round_half_up</span>(p_H_Adm <span class="sc">-</span> p_F_Adm, <span class="dv">2</span>)</span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 14.16</code></pre>
</div>
</div>
<p>La différence de risque peut aussi être automatiquement obtenue avec la fonction <code>arr()</code> du package <code>{effectsize}</code>, comme ceci :</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">arr</span>(tab)</span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>ARR  |       95% CI
-------------------
0.14 | [0.11, 0.17]</code></pre>
</div>
</div>
<p>Le résultat indique que les hommes avaient une différence absolue de taux de réussite de +14 % par rapport aux femmes.</p>
</section>
<section id="risque-relatif" class="level4" data-number="5.2.2.2">
<h4 data-number="5.2.2.2" class="anchored" data-anchor-id="risque-relatif"><span class="header-section-number">5.2.2.2</span> Risque relatif</h4>
<p>Le risque relatif, noté <span class="math inline">\(RR\)</span>, reprend les mêmes informations que celles utilisées pour la différence de risque (<span class="math inline">\(p_{H/Adm}\)</span> et <span class="math inline">\(p_{F/Adm}\)</span>). Ce qui change, c’est qu’il ne s’agit plus d’une différence, mais d’un rapport entre les risques présentés par les groupes comparés. Sa formule pour comparer le groupe des hommes au groupe des femmes dans notre exemple débuté plus haut est la suivante :</p>
<p><span class="math display">\[RR = \frac{{p_{H/Adm}}}{{p_{F/Adm}}}\]</span></p>
<p>Manuellement dans R, on aurait donc :</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a>janitor<span class="sc">::</span><span class="fu">round_half_up</span>(p_H_Adm <span class="sc">/</span> p_F_Adm, <span class="dv">2</span>)</span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.47</code></pre>
</div>
</div>
<p>Le risque relatif peut aussi automatiquement être obtenu avec la fonction <code>riskratio()</code> du package <code>{effectsize}</code> comme ceci :</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="fu">riskratio</span>(tab)</span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Risk ratio |       95% CI
-------------------------
1.47       | [1.35, 1.59]</code></pre>
</div>
</div>
<p>Le résultat indique que le taux de réussite des hommes était 1.47 fois plus élevé que celui des femmes.</p>
</section>
<section id="rapports-des-cotes" class="level4" data-number="5.2.2.3">
<h4 data-number="5.2.2.3" class="anchored" data-anchor-id="rapports-des-cotes"><span class="header-section-number">5.2.2.3</span> Rapports des cotes</h4>
<p>Le rapport des cotes, noté <span class="math inline">\(OR\)</span> pour <em>Odds ratio</em> en anglais, est une statistique dont le calcul peut à nouveau se comprendre à l’aide d’un tableau de contingence. Si l’on reprend le tableau de la <a href="#fig-RiskContTables" class="quarto-xref">Figure&nbsp;<span>5.6</span></a>, on peut dire que la cote pour le fait d’être admis versus le fait d’être refusé dans le groupe des hommes est <span class="math inline">\(n_{1}\)</span>/<span class="math inline">\(n_{3}\)</span> et la cote pour le fait d’être admis versus le fait d’être refusée dans le groupe des femmes est <span class="math inline">\(n_{2}\)</span>/<span class="math inline">\(n_{4}\)</span>. Le rapport des cotes pour les hommes versus celui pour les femmes dans ce cas-là peut se calculer comme ceci :</p>
<p><span class="math display">\[ OR =  \frac{n_{1} / n{_{3}}}{n_{2} / n{_{4}}}\]</span></p>
<p>Le rapport des cotes est toujours ≥0. Une valeur en-dessous de 1 signifie « moins de chances/risques », une valeur de 1 signifie « chances/risques équivalent(e)s », et une valeur au-dessus de 1 signifie « plus de chances ou de risques ». Le chiffre obtenu renseigne toujours sur un niveau de chances pour le groupe au numérateur par rapport au niveau de chances concernant le groupe au dénominateur.</p>
<p>Manuellement dans R, on aurait donc :</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a>janitor<span class="sc">::</span><span class="fu">round_half_up</span>((<span class="dv">1198</span><span class="sc">/</span><span class="dv">1493</span>) <span class="sc">/</span> (<span class="dv">557</span><span class="sc">/</span><span class="dv">1278</span>), <span class="dv">2</span>)</span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.84</code></pre>
</div>
</div>
<p>Le rapport de cotes peut aussi automatiquement être obtenu avec la fonction <code>oddsratio()</code> du package <code>{effectsize}</code> comme ceci :</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="fu">oddsratio</span>(tab)</span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Odds ratio |       95% CI
-------------------------
1.84       | [1.62, 2.09]</code></pre>
</div>
</div>
<p>Le résultat indique que la cote pour le fait d’être admis chez les garçons était 1.84 fois plus élevée que chez les filles.</p>
</section>
</section>
</section>
<section id="résumé" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="résumé"><span class="header-section-number">5.3</span> Résumé</h2>
<ul>
<li>L’analyse graphique de la comparaison de deux groupes de valeurs numériques peut se faire à l’aide de <em>raincloud plots</em>.</li>
<li>L’analyse consistant à comparer deux groupes sur une variable quantitative peut consister à calculer une différence de moyennes standardisée. Les indices de différence de moyennes standardisée non biaisés sont les <span class="math inline">\(g_{s}\)</span> et <span class="math inline">\(g_{av}\)</span> de Hedges en cas de groupes non appariés et les <span class="math inline">\(g_{z}\)</span> et <span class="math inline">\(g_{av}\)</span> de Hedges en cas de groupes appariés et peuvent être calculés respectivement avec les fonctions <code>effectsize::hedges_g()</code> et <code>effectsize::rm_d()</code>. Afin d’éviter la supposition que les variances des groupes comparés sont égales (avec des groupes non appariés) ou pour rendre les résultats d’études avec groupes appariés plus comparables avec les études ayant utilisé des groupes non appariés, le <span class="math inline">\(g_{av}\)</span> de Hedges pourrait être privilégié. Lorsque les conditions de normalité et/ou d’homogénéité des variances ne son pas présentes, mieux vaut utiliser des indicateurs statistiques plus robustes, tels que la corrélation bisériale des rangs qui traduit la notion de dominance d’un groupe sur un autre, et qui peut être obtenue avec la fonction <code>effectsize::rank_biserial()</code>. Un autre indicateur qu’il peut être intéressant de proposer quelles que soient les distributions des données est la probabilité de supériorité, qui s’inscrit dans l’utilisation d’un langage commun, et qui peut être obtenue avec la fonction <code>effectsize::p_superiority()</code>.</li>
<li>L’analyse consistant à comparer deux groupes sur une variable qualitative peut s’effectuer graphiquement à l’aide de diagrammes en barres et numériquement via la différence de risque, le rapport de risque, et le rapport de cotes. Ces derniers indices statistiques peuvent être obtenus respectivement à l’aide des fonctions <code>effectsize::arr()</code>, <code>effectsize::riskratio()</code> et <code>effectsize::oddsatio()</code>.</li>
</ul>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list" style="display: none">
<div id="ref-bickelSexBiasGraduate1975" class="csl-entry" role="listitem">
Bickel, P. J., Hammel, E. A., &amp; O’Connell J, W. (1975). Sex Bias in Graduate Admissions: Data from Berkeley. <em>Science</em>, <em>187</em>(4175), 398‑404. <a href="https://doi.org/10.1126/science.187.4175.398">https://doi.org/10.1126/science.187.4175.398</a>
</div>
<div id="ref-kelleyEffectsNonnormalDistributions2005" class="csl-entry" role="listitem">
Kelley, K. (2005). The <span>Effects</span> of Nonnormal Distributions on Confidence <span>Intervals</span> around the Standardized Mean Difference: Bootstrap and Parametric Confidence Intervals. <em>Educ Psychol Meas</em>, <em>65</em>(1), 51‑69. <a href="https://doi.org/10.1177/0013164404264850">https://doi.org/10.1177/0013164404264850</a>
</div>
<div id="ref-lakensCalculatingReportingEffect2013" class="csl-entry" role="listitem">
Lakens, D. (2013). Calculating and Reporting Effect Sizes to Facilitate Cumulative Science: A Practical Primer for t-Tests and <span>ANOVAs</span>. <em>Front. Psychol.</em>, <em>4</em>. <a href="https://doi.org/10.3389/fpsyg.2013.00863">https://doi.org/10.3389/fpsyg.2013.00863</a>
</div>
<div id="ref-liEffectSizeMeasures2016" class="csl-entry" role="listitem">
Li, J. C.-H. (2016). Effect Size Measures in a Two-Independent-Samples Case with Nonnormal and Nonhomogeneous Data. <em>Behav Res</em>, <em>48</em>(4), 1560‑1574. <a href="https://doi.org/10.3758/s13428-015-0667-z">https://doi.org/10.3758/s13428-015-0667-z</a>
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copié");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copié");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/pydemull\.github\.io\/Analyser-des-donnees-avec-R\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./bivariate_analyses.html" class="pagination-link" aria-label="Analyses bivariées">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Analyses bivariées</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./regressions.html" class="pagination-link" aria-label="Régressions">
        <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Régressions</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Analyser des données avec R a été écrit par Pierre-Yves de Müllenheim.</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/pydemull/Analyser-des-donnees-avec-R/edit/master/two_group_comparison.qmd" class="toc-action"><i class="bi bi-github"></i>Modifier cette page</a></li><li><a href="https://github.com/pydemull/Analyser-des-donnees-avec-R/issues/new" class="toc-action"><i class="bi empty"></i>Faire part d'un problème</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>Ce livre a été généré avec <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer>




</body></html>