{
  "hash": "b46ef7abbcdb6203b1ba446f405c9753",
  "result": {
    "engine": "knitr",
    "markdown": "---\ncrossref:\n  tbl-title: Tableau\n  tbl-prefix: Tableau\n---\n\n::: {.cell}\n\n:::\n\n\n\n# Analyses bivariées\n\nRéaliser une analyse bivariée désigne le fait d'étudier la relation qui peut exister entre deux variables. Dans ce chapitre, nous allons voir les procédures graphiques et calculatoires qui permettent d'étudier et de quantifier le degré de relation pouvant exister entre deux variables dans les cas suivants : entre deux variables quantitatives, et entre deux variables qualitatives. Comme dans le chapitre précédent, l'objectif est ici d'explorer et de décrire les données et leurs relations à l'échelle d'un échantillon, sans pour autant chercher à déterminer l'incertitude qu'il peut exister dans les statistiques calculées en vue de les utiliser pour réaliser une inférence dans la population représentée.\n\n## Relation entre deux variables quantitatives\n\n### Étudier graphiquement la relation\n\nComme dans le cadre d'analyses univariées, une bonne pratique, lorsqu'on étudie une relation bivariée, est de faire un graphique. Avec des variables quantitatives, il s'agit de montrer les valeurs d'une variable en fonction des valeurs de l'autre variable, chose que permet un simple nuage de points. Plusieurs types de relations peuvent alors être rencontrés, ces relations pouvant potentiellement s'apparenter à autant de fonctions mathématiques que l'on connaît. Parmi les plus connues, on a par exemple les relations linéaires, les relations logarithmiques, ou encore les relations quadratiques, qui sont illustrées sur la @fig-relationshipsIllustrations.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Différentes formes de relation entre deux variables quantitatives](bivariate_analyses_files/figure-html/fig-relationshipsIllustrations-1.png){#fig-relationshipsIllustrations width=100%}\n:::\n:::\n\n\nAvec R, pour obtenir un nuage de points à partir d'un jeu de données, il est possible d'utiliser la fonction `ggplot()` en l'associant à la fonction `geom_point()` du package `ggplot2`, comme dans l'exemple ci-dessous qui utilise le jeu de données `mtcars` (qui est intégré à R de base) et les variables `hp` (*gross horsepower*) et `mpg` (*miles/US gallon*). Dans cet exemple dont le résultat est montré sur la @fig-scatterplot, on peut voir que la relation semble globalement linéaire négative (voire curvilinéaire négative si l'on donne de l'importance au point isolé à droite du graphique).\n\n\n::: {.cell out-.width='90%'}\n\n```{.r .cell-code}\nggplot(data = mtcars, aes(x = hp, y = mpg)) + \n  geom_point()\n```\n\n::: {.cell-output-display}\n![Nuage de points montrant les variables hp et mpg du jeu de données mtcars](bivariate_analyses_files/figure-html/fig-scatterplot-1.png){#fig-scatterplot width=672}\n:::\n:::\n\n\n### Étudier numériquement la relation\n\n#### Le coefficient de corrélation de Pearson\n\nLorsque la relation étudiée semble linéaire, l'étude numérique classique consiste à calculer le coefficient de corrélation de Pearson, noté $r$, dont la valeur vise à renseigner dans quelle mesure le nuage de points représentant le lien entre les deux variables étudiées suit une droite. Avant de se lancer dans le calcul du coefficient de corrélation de Pearson pour étudier la relation entre une variable $X$ et une variable $Y$, il peut donc être utile de compléter le nuage de points montré sur la @fig-scatterplot avec une droite d'équation de type $Y = aX + b$ (@fig-scatterplotLine). Cette équation serait la meilleure modélisation possible de la relation linéaire entre $X$ et $Y$, de telle sorte que parmi l'infinité d'équations qui pourraient lier $X$ à $Y$, c'est cette équation qui au total donnerait la plus petite erreur lorsque l'on voudrait prédire $Y$ à partir de $X$. Si $X$ et $Y$ sont liées de manière linéaire, alors le nuage des points relatifs aux deux variables devrait s'étaler le long de cette droite. Pour obtenir cette droite en plus du nuage de points, il est possible d'utiliser la fonction `geom_smooth()` du package `ggplot2`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = mtcars, aes(x = hp, y = mpg)) + \n  geom_point() +\n  geom_smooth(formula = y ~ x, method = \"lm\", se = FALSE)\n```\n\n::: {.cell-output-display}\n![Nuage de points avec droite de régression pour les variables hp et mpg du jeu de données mtcars](bivariate_analyses_files/figure-html/fig-scatterplotLine-1.png){#fig-scatterplotLine width=90%}\n:::\n:::\n\n\nDans la fonction `geom_smooth()` qui a été utilisée dans l'exemple ci-dessus, on note que l'argument `formula` pourrait être considéré comme facultatif car il s'agit ici de la configuration par défaut de la fonction. En revanche, l'argument `method` doit être ici configuré avec `\"lm\"` (pour *linear model*) car ce n'est pas la méthode graphique configurée par défaut dans la fonction. Enfin, l'argument `se` permet de montrer ou non un intervalle de confiance autour de la droite de régression, ce qui n'a pas été activé ici (par défaut, l'argument `se` est configuré pour montrer cet intervalle de confiance). Dans l'exemple montré ci-dessus, la représentation graphique encourage fortement à penser que l'un des types de relations à envisager prioritairement dans l'étude des deux variables est la relation linéaire. Cette information rend pertinente l'utilisation du coefficient de corrélation de Pearson pour une étude numérique de la relation en question.\n\nLa valeur du coefficient de corrélation de Pearson peut aller de 1 (suggérant une relation linéaire positive parfaite) à -1 (suggérant une relation linéaire négative parfaite). Des valeurs proches de 0 suggèreraient une abscence de relation linéaire. La formule du coefficient de corrélation de Pearson ($r$) pour un échantillon est la suivante : \n\n$$r_{X,Y} =  {\\frac{COV_{X,Y}}{\\hat{\\sigma}_{X} \\hat{\\sigma}_{Y}}} =  {\\frac{\\sum_{i=1}^{N} (X{i} - \\overline{X}) (Y{i} - \\overline{Y})}{N-1}} {\\frac{1}{\\hat{\\sigma}_{X} \\hat{\\sigma}_{Y}}},$$\n\n$COV$ désignant la covariance entre les variables $X$ et $Y$, $X{i}$ et $Y{i}$ les valeurs de $X$ et $Y$ pour une observation $i$, $\\overline{X}$ et $\\overline{Y}$ les moyennes respectives des variables $X$ et $Y$, $N$ le nombre d'observations, et $\\hat{\\sigma}_{X}$ et $\\hat{\\sigma}_{Y}$ les écarts-types respectifs des variables $X$ et $Y$. Cette formule indique que le coefficient de corrélation de Pearson s'obtient en divisant la covariance des deux variables étudiées par le produit de leurs écarts-types respectifs. \n\nLe @tbl-tablecov montre les premières étapes du calcul de la covariance pour des couples de variables fictifs $(X1,Y1)$, $(X1,Y2)$, et $(X1,Y3)$. En particulier, la partie droite du tableau (de X1Y1 à X1Y3) montre le calcul du produit $(X{i} - \\overline{X}) (Y{i} - \\overline{Y})$ pour les différents couples de variables et cela pour chaque ligne du jeu de données.\n\n\n::: {#tbl-tablecov .cell tbl-cap='Illustration de calculs de covariance'}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-7c717cfe{}.cl-7c674cc0{font-family:'Arial';font-size:11pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-7c674cde{font-family:'Arial';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-7c6ad610{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-7c6afa32{width:0.472in;background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1.5pt solid rgba(0, 0, 0, 1.00);border-top: 1.5pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7c6afa3c{width:0.506in;background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1.5pt solid rgba(0, 0, 0, 1.00);border-top: 1.5pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7c6afa3d{width:0.659in;background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1.5pt solid rgba(0, 0, 0, 1.00);border-top: 1.5pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7c6afa3e{width:1.058in;background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1.5pt solid rgba(0, 0, 0, 1.00);border-top: 1.5pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7c6afa46{width:0.472in;background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7c6afa47{width:0.506in;background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7c6afa50{width:0.659in;background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7c6afa51{width:1.058in;background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7c6afa5a{width:0.472in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7c6afa5b{width:0.506in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7c6afa5c{width:0.659in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7c6afa64{width:1.058in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7c6afa65{width:0.472in;background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7c6afa66{width:0.506in;background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7c6afa6e{width:0.659in;background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7c6afa6f{width:1.058in;background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7c6afa78{width:0.472in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7c6afa79{width:0.506in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7c6afa7a{width:0.659in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7c6afa82{width:1.058in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7c6afa83{width:0.472in;background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1.5pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7c6afa84{width:0.506in;background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1.5pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7c6afa8c{width:0.659in;background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1.5pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7c6afa8d{width:1.058in;background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1.5pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-7c717cfe'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-7c6afa32\"><p class=\"cl-7c6ad610\"><span class=\"cl-7c674cc0\">X1</span></p></th><th class=\"cl-7c6afa32\"><p class=\"cl-7c6ad610\"><span class=\"cl-7c674cc0\">Y1</span></p></th><th class=\"cl-7c6afa32\"><p class=\"cl-7c6ad610\"><span class=\"cl-7c674cc0\">Y2</span></p></th><th class=\"cl-7c6afa3c\"><p class=\"cl-7c6ad610\"><span class=\"cl-7c674cc0\">Y3</span></p></th><th class=\"cl-7c6afa3d\"><p class=\"cl-7c6ad610\"><span class=\"cl-7c674cc0\">X1Y1</span></p></th><th class=\"cl-7c6afa3e\"><p class=\"cl-7c6ad610\"><span class=\"cl-7c674cc0\">X1Y2</span></p></th><th class=\"cl-7c6afa3d\"><p class=\"cl-7c6ad610\"><span class=\"cl-7c674cc0\">X1Y3</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-7c6afa46\"><p class=\"cl-7c6ad610\"><span class=\"cl-7c674cde\">0</span></p></td><td class=\"cl-7c6afa46\"><p class=\"cl-7c6ad610\"><span class=\"cl-7c674cde\">0</span></p></td><td class=\"cl-7c6afa46\"><p class=\"cl-7c6ad610\"><span class=\"cl-7c674cde\">0</span></p></td><td class=\"cl-7c6afa47\"><p class=\"cl-7c6ad610\"><span class=\"cl-7c674cde\">0</span></p></td><td class=\"cl-7c6afa50\"><p class=\"cl-7c6ad610\"><span class=\"cl-7c674cde\">36</span></p></td><td class=\"cl-7c6afa51\"><p class=\"cl-7c6ad610\"><span class=\"cl-7c674cde\">40.285714</span></p></td><td class=\"cl-7c6afa50\"><p class=\"cl-7c6ad610\"><span class=\"cl-7c674cde\">-36</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-7c6afa5a\"><p class=\"cl-7c6ad610\"><span class=\"cl-7c674cde\">2</span></p></td><td class=\"cl-7c6afa5a\"><p class=\"cl-7c6ad610\"><span class=\"cl-7c674cde\">2</span></p></td><td class=\"cl-7c6afa5a\"><p class=\"cl-7c6ad610\"><span class=\"cl-7c674cde\">1</span></p></td><td class=\"cl-7c6afa5b\"><p class=\"cl-7c6ad610\"><span class=\"cl-7c674cde\">-2</span></p></td><td class=\"cl-7c6afa5c\"><p class=\"cl-7c6ad610\"><span class=\"cl-7c674cde\">16</span></p></td><td class=\"cl-7c6afa64\"><p class=\"cl-7c6ad610\"><span class=\"cl-7c674cde\">22.857143</span></p></td><td class=\"cl-7c6afa5c\"><p class=\"cl-7c6ad610\"><span class=\"cl-7c674cde\">-16</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-7c6afa65\"><p class=\"cl-7c6ad610\"><span class=\"cl-7c674cde\">4</span></p></td><td class=\"cl-7c6afa65\"><p class=\"cl-7c6ad610\"><span class=\"cl-7c674cde\">4</span></p></td><td class=\"cl-7c6afa65\"><p class=\"cl-7c6ad610\"><span class=\"cl-7c674cde\">15</span></p></td><td class=\"cl-7c6afa66\"><p class=\"cl-7c6ad610\"><span class=\"cl-7c674cde\">-4</span></p></td><td class=\"cl-7c6afa6e\"><p class=\"cl-7c6ad610\"><span class=\"cl-7c674cde\">4</span></p></td><td class=\"cl-7c6afa6f\"><p class=\"cl-7c6ad610\"><span class=\"cl-7c674cde\">-16.571429</span></p></td><td class=\"cl-7c6afa6e\"><p class=\"cl-7c6ad610\"><span class=\"cl-7c674cde\">-4</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-7c6afa78\"><p class=\"cl-7c6ad610\"><span class=\"cl-7c674cde\">6</span></p></td><td class=\"cl-7c6afa78\"><p class=\"cl-7c6ad610\"><span class=\"cl-7c674cde\">6</span></p></td><td class=\"cl-7c6afa78\"><p class=\"cl-7c6ad610\"><span class=\"cl-7c674cde\">5</span></p></td><td class=\"cl-7c6afa79\"><p class=\"cl-7c6ad610\"><span class=\"cl-7c674cde\">-6</span></p></td><td class=\"cl-7c6afa7a\"><p class=\"cl-7c6ad610\"><span class=\"cl-7c674cde\">0</span></p></td><td class=\"cl-7c6afa82\"><p class=\"cl-7c6ad610\"><span class=\"cl-7c674cde\">0.000000</span></p></td><td class=\"cl-7c6afa7a\"><p class=\"cl-7c6ad610\"><span class=\"cl-7c674cde\">0</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-7c6afa65\"><p class=\"cl-7c6ad610\"><span class=\"cl-7c674cde\">8</span></p></td><td class=\"cl-7c6afa65\"><p class=\"cl-7c6ad610\"><span class=\"cl-7c674cde\">8</span></p></td><td class=\"cl-7c6afa65\"><p class=\"cl-7c6ad610\"><span class=\"cl-7c674cde\">11</span></p></td><td class=\"cl-7c6afa66\"><p class=\"cl-7c6ad610\"><span class=\"cl-7c674cde\">-8</span></p></td><td class=\"cl-7c6afa6e\"><p class=\"cl-7c6ad610\"><span class=\"cl-7c674cde\">4</span></p></td><td class=\"cl-7c6afa6f\"><p class=\"cl-7c6ad610\"><span class=\"cl-7c674cde\">8.571429</span></p></td><td class=\"cl-7c6afa6e\"><p class=\"cl-7c6ad610\"><span class=\"cl-7c674cde\">-4</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-7c6afa5a\"><p class=\"cl-7c6ad610\"><span class=\"cl-7c674cde\">10</span></p></td><td class=\"cl-7c6afa5a\"><p class=\"cl-7c6ad610\"><span class=\"cl-7c674cde\">10</span></p></td><td class=\"cl-7c6afa5a\"><p class=\"cl-7c6ad610\"><span class=\"cl-7c674cde\">3</span></p></td><td class=\"cl-7c6afa5b\"><p class=\"cl-7c6ad610\"><span class=\"cl-7c674cde\">-10</span></p></td><td class=\"cl-7c6afa5c\"><p class=\"cl-7c6ad610\"><span class=\"cl-7c674cde\">16</span></p></td><td class=\"cl-7c6afa64\"><p class=\"cl-7c6ad610\"><span class=\"cl-7c674cde\">-14.857143</span></p></td><td class=\"cl-7c6afa5c\"><p class=\"cl-7c6ad610\"><span class=\"cl-7c674cde\">-16</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-7c6afa83\"><p class=\"cl-7c6ad610\"><span class=\"cl-7c674cde\">12</span></p></td><td class=\"cl-7c6afa83\"><p class=\"cl-7c6ad610\"><span class=\"cl-7c674cde\">12</span></p></td><td class=\"cl-7c6afa83\"><p class=\"cl-7c6ad610\"><span class=\"cl-7c674cde\">12</span></p></td><td class=\"cl-7c6afa84\"><p class=\"cl-7c6ad610\"><span class=\"cl-7c674cde\">-12</span></p></td><td class=\"cl-7c6afa8c\"><p class=\"cl-7c6ad610\"><span class=\"cl-7c674cde\">36</span></p></td><td class=\"cl-7c6afa8d\"><p class=\"cl-7c6ad610\"><span class=\"cl-7c674cde\">31.714286</span></p></td><td class=\"cl-7c6afa8c\"><p class=\"cl-7c6ad610\"><span class=\"cl-7c674cde\">-36</span></p></td></tr></tbody></table></div>\n```\n\n:::\n:::\n\n\nCe que ce tableau montre, c'est que plus les deux variables étudiées évolueront de manière consistante dans des sens identiques comme avec $X1$ et $Y1$, ou de manière consistante dans des sens opposés comme avec $X1$ et $Y3$, plus les produits $(X{i} - \\overline{X}) (Y{i} - \\overline{Y})$ donneront respectivement des grands scores positifs ou des grands scores négatifs, et moins les scores $(X{i} - \\overline{X}) (Y{i} - \\overline{Y})$ à additionner pour le calcul de la covariance s'annuleront. En effet, avec une relation relativement linéaire et positive les scores seront plus systématiquement positifs, et avec une relation relativement linéaire et négative les scores seront plus systématiquement négatifs. Toutefois, lorsqu'on aura des variables qui n'évolueront pas de manière consistante dans le même sens ou dans un sens opposé comme avec $X1$ et $Y2$, les scores positifs et négatifs liés aux calculs $(X{i} - \\overline{X}) (Y{i} - \\overline{Y})$ auront tendance à s'annuler et donneront lieu à une somme des scores $(X{i} - \\overline{X}) (Y{i} - \\overline{Y})$ diminuée, et donc à une covariance et à un coefficient de corrélation de Pearson tirés vers 0. Ces différents cas de figure et les calculs $(X{i} - \\overline{X}) (Y{i} - \\overline{Y})$ correspondants sont illustrés sur la @fig-graphCov. Sur cette figure, chaque carré correspond au calcul $(X{i} - \\overline{X}) (Y{i} - \\overline{Y})$, le carré étant bleu lorsque le résultat du calcul est positif, et rouge lorsque le résultat est négatif. L'aire d'un carré illustre la grandeur du score issu du calcul. Sur les graphiques de gauche et de droite de la figure, on distingue une relation linéaire parfaite, ce qui maximise les scores à additionner pour le calcul de la covariance, dans le positif pour le graphique de gauche et dans le négatif pour le graphique de droite. Sur le graphique du milieu, on remarque que le manque de relation linéaire donne lieu à des carrés à la fois bleus et rouges, indiquant que les scores associés aux calculs $(X{i} - \\overline{X}) (Y{i} - \\overline{Y})$ de la covariance s'annulent et diminuent ainsi la valeur finale de la covariance.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Illustration du calcul de la covariance](bivariate_analyses_files/figure-html/fig-graphCov-1.png){#fig-graphCov width=100%}\n:::\n:::\n\n\nDans R, le coefficient de corrélation de Pearson peut être obtenu avec la fonction `cor()`. Dans l'exemple ci-dessous qui reprend les variables du jeu de données `mtcars` utilisées plus haut, on observe un coefficient négatif, relativement proche de -1, suggérant une relation relativement linéaire et négative entre les variables étudiées.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor(x = mtcars$hp, y = mtcars$mpg, method = \"pearson\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.7761684\n```\n\n\n:::\n:::\n\n\nToutefois, la fonction `cor.test()` sera plus intéressante pour la suite car elle permet de calculer des indices statistiques de probabilité qui seront nécessaires dès lors qu'il s'agira de chercher à inférer la valeur d'une corrélation dans une population d'où l'échantillon étudié provient. La valeur de la corrélation est  donnée à la fin de la liste des informations qui apparaissent suite à l'activation de la fonction.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor.test(x = mtcars$hp, y = mtcars$mpg, method = \"pearson\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's product-moment correlation\n\ndata:  mtcars$hp and mtcars$mpg\nt = -6.7424, df = 30, p-value = 1.788e-07\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n -0.8852686 -0.5860994\nsample estimates:\n       cor \n-0.7761684 \n```\n\n\n:::\n:::\n\n\nSur la base de travaux antérieurs, Hopkins et al. [-@hopkinsProgressiveStatisticsStudies2009] ont fait une proposition de classification pour qualifier la valeur du coefficient de corrélation qui serait obtenue dans le cadre d'une relation linéaire. Cette proposition est montrée dans le @tbl-correlationtable :\n\n\n::: {#tbl-correlationtable .cell tbl-cap='Proposition de termes qualifiant l\\'importance d\\'une corrélation'}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-7d5f8c6e{}.cl-7d5627b4{font-family:'Arial';font-size:11pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-7d5627c8{font-family:'Arial';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-7d596cda{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-7d599318{width:0.701in;background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1.5pt solid rgba(0, 0, 0, 1.00);border-top: 1.5pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7d599319{width:0.947in;background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1.5pt solid rgba(0, 0, 0, 1.00);border-top: 1.5pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7d599322{width:0.82in;background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1.5pt solid rgba(0, 0, 0, 1.00);border-top: 1.5pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7d599323{width:1.16in;background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1.5pt solid rgba(0, 0, 0, 1.00);border-top: 1.5pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7d59932c{width:1.805in;background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1.5pt solid rgba(0, 0, 0, 1.00);border-top: 1.5pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7d59932d{width:0.701in;background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1.5pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7d599336{width:0.947in;background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1.5pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7d599337{width:0.82in;background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1.5pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7d599338{width:1.16in;background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1.5pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7d599340{width:1.805in;background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1.5pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-7d5f8c6e'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-7d599318\"><p class=\"cl-7d596cda\"><span class=\"cl-7d5627b4\">Petite</span></p></th><th class=\"cl-7d599319\"><p class=\"cl-7d596cda\"><span class=\"cl-7d5627b4\">Moyenne</span></p></th><th class=\"cl-7d599322\"><p class=\"cl-7d596cda\"><span class=\"cl-7d5627b4\">Grande</span></p></th><th class=\"cl-7d599323\"><p class=\"cl-7d596cda\"><span class=\"cl-7d5627b4\">Très grande</span></p></th><th class=\"cl-7d59932c\"><p class=\"cl-7d596cda\"><span class=\"cl-7d5627b4\">Extrêmement grande</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-7d59932d\"><p class=\"cl-7d596cda\"><span class=\"cl-7d5627c8\">0.1</span></p></td><td class=\"cl-7d599336\"><p class=\"cl-7d596cda\"><span class=\"cl-7d5627c8\">0.3</span></p></td><td class=\"cl-7d599337\"><p class=\"cl-7d596cda\"><span class=\"cl-7d5627c8\">0.5</span></p></td><td class=\"cl-7d599338\"><p class=\"cl-7d596cda\"><span class=\"cl-7d5627c8\">0.7</span></p></td><td class=\"cl-7d599340\"><p class=\"cl-7d596cda\"><span class=\"cl-7d5627c8\">0.9</span></p></td></tr></tbody></table></div>\n```\n\n:::\n:::\n\n\nPour visualiser le lien que l'on peut faire entre la forme du nuage de points et la valeur du coefficient de corrélation de Pearson que l'on peut obtenir, la page web proposée par Kristoffer Magnusson (https://rpsychologist.com/correlation) peut être particulièrement intéressante. Cette page web donne la possibilité de faire varier manuellement la valeur du coefficient de corrélation de Pearson pour ensuite voir un nuage de points type correspondant à cette valeur. Faites un essai !\n\nÀ noter que la valeur du coefficient de corrélation de Pearson est dépendante du degré de variabilité des valeurs autour des tendances centrales des variables concernées. [@halperinSpuriousCorrelationsCauses1986]. En ce sens, si dans deux études différentes les variables étudiées n'ont pas les mêmes niveaux de variabilité, les valeurs des coefficients de corrélation de Pearson ne seront pas vraiment comparables, en sachant que c'est l'étude qui présentera l'échantillon avec la plus grande variabilité qui aura plus de chances de présenter une valeur de coefficient de corrélation de Pearson plus élevée.\n\nUn cas particulier illustrant l'influence du degré de dispersion sur la relation étudiée est montré sur la @fig-simpsonquant. Cet exemple a pour but de montrer que l'étude d'une relation entre deux variables quantitatives peut aboutir à des conclusions radicalement différentes selon que l'on conduit les analyses à l'échelle d'un groupe entier ou que l'on sépare les analyses par groupe de caractéristiques, en particulier lorsque la distribution des données par groupe est radicalement différente de celle obtenue à l'échelle du groupe entier. Sur la gauche de la @fig-simpsonquant, le nuage de points représente la relation entre deux variables à l'échelle de l'ensemble du groupe étudié. La variabilité possible pour les deux variables étudiées (V1 et V2 dans l'exemple) est alors maximale. Toutefois, ces données appartiennent en réalité à des sous-groupes distincts (cf. couleurs sur le graphique de droite de la @fig-simpsonquant). L'analyse par sous-groupe diminue la variabilité à la fois pour V1 et V2, donnant même lieu ici à des relations de sens opposé à celui observé à l'échelle de l'ensemble du groupe ! Cette situation correspond à ce qu'on appelle un paradoxe de Simpson, lequel se présente lorsque le phénomène que l'on peut observer avec une vue globale est annulé voire inversé lors d'une analyse par sous-groupe. Ici, la grande variabilité associée aux données du graphique de gauche de la @fig-simpsonquant crée une relation artificiellement et donc faussement positive entre V1 et V2. C'est l'analyse par sous-groupe qui permet de révéler la vraie nature de la relation étudiée.\n\n\n::: {#fig-simpsonquant .cell}\n::: {.cell-output-display}\n![Données obtenues grâce à la fonction simulate_simpson() du package bayestestR](bivariate_analyses_files/figure-html/fig-simpsonquant-1.png){#fig-simpsonquant width=90%}\n:::\n\nInfluence du niveau d'analyse (groupe entier vs. sous-groupes) sur la corrélation observée entre deux variables quantitatives\n:::\n\n\nEn outre, la valeur du coefficient de corrélation de Pearson peut être influencée par des valeurs extrêmes, comme montré sur la @fig-spuriousCorrelationBis. Les deux graphiques de cette figure montrent exactement les mêmes données, à ceci près que sur le graphique de droite, on a remplacé en ordonnées une valeur du graphique de gauche pour lui donner la valeur de 10. L'influence de cette simple action sur la valeur du coefficient de corrélation de Pearson est nette. Ceci montre qu'il faut faire attention aux valeurs extrêmes qui pourraient grandement influencer la variabilité des données d'une variable et au final la valeur de corrélation obtenue, notamment en présence d'échantillons de taille relativement faible. Dans le cas où la valeur du coefficient de corrélation de Pearson serait très influencée par une valeur, il pourrait être une bonne pratique de calculer la valeur du coefficient de corrélation de Pearson avec et sans cette valeur afin de pouvoir quantifier son influence sur la relation étudiée [@halperinSpuriousCorrelationsCauses1986]. Une alternative pourrait être aussi d'étudier la relation à l'aide d'autres types de coefficients que celui de Pearson, tels que celui de Spearman, présenté plus bas. Cet exemple doit faire prendre conscience qu'il n'est pas toujours pertinent de calculer le coefficient de corrélation de Pearson. En ce sens, lorsqu'on cherche à inférer la valeur du coefficient de corrélation de Pearson dans la population étudiée, il convient de vérifier certains prérequis, lesquels sont abordés plus loin dans ce livre. \n\n\n::: {.cell}\n::: {.cell-output-display}\n![Influence d'une valeur extrême sur la valeur du coefficient de corrélation de Pearson en présence d'un petit échantillon](bivariate_analyses_files/figure-html/fig-spuriousCorrelationBis-1.png){#fig-spuriousCorrelationBis width=90%}\n:::\n:::\n\n\nLorsque la relation étudiée ne semble pas linéaire mais s'apparente assez clairement à d'autres fonctions mathématiques, telles que des relations logarithmiques ou polynomiales, il est possible de transformer une des variables, voire les deux, pour rendre la relation linéaire et à nouveau étudiable à l'aide du coefficient de corrélation de Pearson [@halperinSpuriousCorrelationsCauses1986]. Toutefois, il est aussi possible de créer des modèles de régression non linéaires afin de regarder si ces modèles correspondent bien aux données. La détermination et la validation d'un modèle non linéaire qui correspondrait bien aux données confirmerait alors que la relation étudiée a une forme particulière et potentiellement prédictible. Les procédures pour explorer différents modèles de régression (linéaires et non linéaires) sont abordées au chapitre suivant. Enfin, une dernière alternative possible, pour étudier la relation entre deux variables quantitatives dont les distributions ne permettraient pas d'utiliser correctement le coefficient de corrélation de Pearson, serait l'utilisation de coefficients de corrélation basés sur les rangs, tels que le coefficient de corrélation de Spearman.\n\n#### Le coefficient de corrélation de Spearman\n\nLorsque le coefficient de corrélation de Pearson ne permet pas de caractériser fiablement le degré de relation linéaire **entre les valeurs** de deux variables (e.g., en présence de valeurs aberrantes au sein d'un échantillon de petite taille), une alternative peut être d'étudier le degré de relation linéaire **entre les rangs** de ces deux variables. Le rang, c'est le classement (ou la position) d'une observation donnée au sein d'une variable en fonction de sa valeur. Dans une variable, les observations avec les valeurs les plus faibles seront associées aux rangs les plus bas alors que les observations avec les valeurs les plus élevées seront associées aux rangs les plus élevés. Une illustration de la notion de rang est proposée dans le @tbl-tableranks pour la variable `hp` du jeu de données `mtcars`. Dans ce tableau, les lignes ont été ordonnées sur la base des rangs de la variable `hp`. On pourra remarquer que dans le tableau, nous avons ce qu'on appelle des ex-aequos, c'est-à-dire que plusieurs observations peuvent présenter les mêmes valeurs, et donc avoir le même rang.\n\n\n::: {#tbl-tableranks .cell tbl-cap='Illustration de la notion de rang pour une variable quantitative'}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-7e65acf6{}.cl-7e582298{font-family:'Arial';font-size:11pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-7e5822ac{font-family:'Arial';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-7e5def5c{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-7e5e1694{width:1.066in;background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1.5pt solid rgba(0, 0, 0, 1.00);border-top: 1.5pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7e5e169e{width:0.947in;background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1.5pt solid rgba(0, 0, 0, 1.00);border-top: 1.5pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7e5e16a8{width:1.066in;background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7e5e16b2{width:0.947in;background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7e5e16b3{width:1.066in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7e5e16bc{width:0.947in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7e5e16bd{width:1.066in;background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7e5e16be{width:0.947in;background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7e5e16c6{width:1.066in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7e5e16c7{width:0.947in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7e5e16d0{width:1.066in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7e5e16d1{width:0.947in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-7e65acf6'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-7e5e1694\"><p class=\"cl-7e5def5c\"><span class=\"cl-7e582298\">hp (valeur)</span></p></th><th class=\"cl-7e5e169e\"><p class=\"cl-7e5def5c\"><span class=\"cl-7e582298\">hp (rang)</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-7e5e16a8\"><p class=\"cl-7e5def5c\"><span class=\"cl-7e5822ac\">52</span></p></td><td class=\"cl-7e5e16b2\"><p class=\"cl-7e5def5c\"><span class=\"cl-7e5822ac\">1.0</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-7e5e16b3\"><p class=\"cl-7e5def5c\"><span class=\"cl-7e5822ac\">62</span></p></td><td class=\"cl-7e5e16bc\"><p class=\"cl-7e5def5c\"><span class=\"cl-7e5822ac\">2.0</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-7e5e16bd\"><p class=\"cl-7e5def5c\"><span class=\"cl-7e5822ac\">65</span></p></td><td class=\"cl-7e5e16be\"><p class=\"cl-7e5def5c\"><span class=\"cl-7e5822ac\">3.0</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-7e5e16b3\"><p class=\"cl-7e5def5c\"><span class=\"cl-7e5822ac\">66</span></p></td><td class=\"cl-7e5e16bc\"><p class=\"cl-7e5def5c\"><span class=\"cl-7e5822ac\">4.5</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-7e5e16a8\"><p class=\"cl-7e5def5c\"><span class=\"cl-7e5822ac\">66</span></p></td><td class=\"cl-7e5e16b2\"><p class=\"cl-7e5def5c\"><span class=\"cl-7e5822ac\">4.5</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-7e5e16b3\"><p class=\"cl-7e5def5c\"><span class=\"cl-7e5822ac\">91</span></p></td><td class=\"cl-7e5e16bc\"><p class=\"cl-7e5def5c\"><span class=\"cl-7e5822ac\">6.0</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-7e5e16bd\"><p class=\"cl-7e5def5c\"><span class=\"cl-7e5822ac\">93</span></p></td><td class=\"cl-7e5e16be\"><p class=\"cl-7e5def5c\"><span class=\"cl-7e5822ac\">7.0</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-7e5e16b3\"><p class=\"cl-7e5def5c\"><span class=\"cl-7e5822ac\">95</span></p></td><td class=\"cl-7e5e16bc\"><p class=\"cl-7e5def5c\"><span class=\"cl-7e5822ac\">8.0</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-7e5e16a8\"><p class=\"cl-7e5def5c\"><span class=\"cl-7e5822ac\">97</span></p></td><td class=\"cl-7e5e16b2\"><p class=\"cl-7e5def5c\"><span class=\"cl-7e5822ac\">9.0</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-7e5e16b3\"><p class=\"cl-7e5def5c\"><span class=\"cl-7e5822ac\">105</span></p></td><td class=\"cl-7e5e16bc\"><p class=\"cl-7e5def5c\"><span class=\"cl-7e5822ac\">10.0</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-7e5e16a8\"><p class=\"cl-7e5def5c\"><span class=\"cl-7e5822ac\">109</span></p></td><td class=\"cl-7e5e16b2\"><p class=\"cl-7e5def5c\"><span class=\"cl-7e5822ac\">11.0</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-7e5e16c6\"><p class=\"cl-7e5def5c\"><span class=\"cl-7e5822ac\">110</span></p></td><td class=\"cl-7e5e16c7\"><p class=\"cl-7e5def5c\"><span class=\"cl-7e5822ac\">13.0</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-7e5e16bd\"><p class=\"cl-7e5def5c\"><span class=\"cl-7e5822ac\">110</span></p></td><td class=\"cl-7e5e16be\"><p class=\"cl-7e5def5c\"><span class=\"cl-7e5822ac\">13.0</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-7e5e16c6\"><p class=\"cl-7e5def5c\"><span class=\"cl-7e5822ac\">110</span></p></td><td class=\"cl-7e5e16c7\"><p class=\"cl-7e5def5c\"><span class=\"cl-7e5822ac\">13.0</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-7e5e16bd\"><p class=\"cl-7e5def5c\"><span class=\"cl-7e5822ac\">113</span></p></td><td class=\"cl-7e5e16be\"><p class=\"cl-7e5def5c\"><span class=\"cl-7e5822ac\">15.0</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-7e5e16c6\"><p class=\"cl-7e5def5c\"><span class=\"cl-7e5822ac\">123</span></p></td><td class=\"cl-7e5e16c7\"><p class=\"cl-7e5def5c\"><span class=\"cl-7e5822ac\">16.5</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-7e5e16bd\"><p class=\"cl-7e5def5c\"><span class=\"cl-7e5822ac\">123</span></p></td><td class=\"cl-7e5e16be\"><p class=\"cl-7e5def5c\"><span class=\"cl-7e5822ac\">16.5</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-7e5e16b3\"><p class=\"cl-7e5def5c\"><span class=\"cl-7e5822ac\">150</span></p></td><td class=\"cl-7e5e16bc\"><p class=\"cl-7e5def5c\"><span class=\"cl-7e5822ac\">18.5</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-7e5e16a8\"><p class=\"cl-7e5def5c\"><span class=\"cl-7e5822ac\">150</span></p></td><td class=\"cl-7e5e16b2\"><p class=\"cl-7e5def5c\"><span class=\"cl-7e5822ac\">18.5</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-7e5e16b3\"><p class=\"cl-7e5def5c\"><span class=\"cl-7e5822ac\">175</span></p></td><td class=\"cl-7e5e16bc\"><p class=\"cl-7e5def5c\"><span class=\"cl-7e5822ac\">21.0</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-7e5e16a8\"><p class=\"cl-7e5def5c\"><span class=\"cl-7e5822ac\">175</span></p></td><td class=\"cl-7e5e16b2\"><p class=\"cl-7e5def5c\"><span class=\"cl-7e5822ac\">21.0</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-7e5e16b3\"><p class=\"cl-7e5def5c\"><span class=\"cl-7e5822ac\">175</span></p></td><td class=\"cl-7e5e16bc\"><p class=\"cl-7e5def5c\"><span class=\"cl-7e5822ac\">21.0</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-7e5e16a8\"><p class=\"cl-7e5def5c\"><span class=\"cl-7e5822ac\">180</span></p></td><td class=\"cl-7e5e16b2\"><p class=\"cl-7e5def5c\"><span class=\"cl-7e5822ac\">24.0</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-7e5e16b3\"><p class=\"cl-7e5def5c\"><span class=\"cl-7e5822ac\">180</span></p></td><td class=\"cl-7e5e16bc\"><p class=\"cl-7e5def5c\"><span class=\"cl-7e5822ac\">24.0</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-7e5e16a8\"><p class=\"cl-7e5def5c\"><span class=\"cl-7e5822ac\">180</span></p></td><td class=\"cl-7e5e16b2\"><p class=\"cl-7e5def5c\"><span class=\"cl-7e5822ac\">24.0</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-7e5e16b3\"><p class=\"cl-7e5def5c\"><span class=\"cl-7e5822ac\">205</span></p></td><td class=\"cl-7e5e16bc\"><p class=\"cl-7e5def5c\"><span class=\"cl-7e5822ac\">26.0</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-7e5e16a8\"><p class=\"cl-7e5def5c\"><span class=\"cl-7e5822ac\">215</span></p></td><td class=\"cl-7e5e16b2\"><p class=\"cl-7e5def5c\"><span class=\"cl-7e5822ac\">27.0</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-7e5e16c6\"><p class=\"cl-7e5def5c\"><span class=\"cl-7e5822ac\">230</span></p></td><td class=\"cl-7e5e16c7\"><p class=\"cl-7e5def5c\"><span class=\"cl-7e5822ac\">28.0</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-7e5e16a8\"><p class=\"cl-7e5def5c\"><span class=\"cl-7e5822ac\">245</span></p></td><td class=\"cl-7e5e16b2\"><p class=\"cl-7e5def5c\"><span class=\"cl-7e5822ac\">29.5</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-7e5e16b3\"><p class=\"cl-7e5def5c\"><span class=\"cl-7e5822ac\">245</span></p></td><td class=\"cl-7e5e16bc\"><p class=\"cl-7e5def5c\"><span class=\"cl-7e5822ac\">29.5</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-7e5e16bd\"><p class=\"cl-7e5def5c\"><span class=\"cl-7e5822ac\">264</span></p></td><td class=\"cl-7e5e16be\"><p class=\"cl-7e5def5c\"><span class=\"cl-7e5822ac\">31.0</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-7e5e16d0\"><p class=\"cl-7e5def5c\"><span class=\"cl-7e5822ac\">335</span></p></td><td class=\"cl-7e5e16d1\"><p class=\"cl-7e5def5c\"><span class=\"cl-7e5822ac\">32.0</span></p></td></tr></tbody></table></div>\n```\n\n:::\n:::\n\n\nLe fait d'étudier l'existence d'une relation linéaire entre les rangs et non plus entre les valeurs de deux variables permet de s'affranchir de l'influence possible de valeurs très extrêmes, dans l'une et/ou l'autre variable, sur le calcul final de la corrélation. Pour déterminer alors la valeur de la corrélation, une manière de procéder est d'appliquer la méthode de calcul du coefficient de corrélation de Pearson en utilisant non plus les valeurs des variables, mais les rangs correspondants. Cette methode, c'est celle du calcul du coefficient de corrélation de Spearman (*rho*). Si l'on suit *stricto sensu* cette définition, nous pourrions alors utiliser le code suivant pour avoir le coefficient de corrélation de Spearman :\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor(x = rank(mtcars$hp), y = rank(mtcars$mpg), method = \"pearson\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.8946646\n```\n\n\n:::\n:::\n\n\nToutefois, il existe une manière plus directe d'écrire les choses avec la fonction `cor`, qui contient un argument spécifiquement dédié au calcul du coefficient *rho* de Spearman : \n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor(x = mtcars$hp, y = mtcars$mpg, method = \"spearman\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.8946646\n```\n\n\n:::\n:::\n\n\nLa fonction `cor.test` permet aussi de calculer le coefficient de corrélation de Spearman en fournissant aussi des informations potentiellement intéressantes pour donner une idée de la significativité statistique de l'estimation de *rho* dans la population étudiée.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor.test(x = mtcars$hp, y = mtcars$mpg, method = \"spearman\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tSpearman's rank correlation rho\n\ndata:  mtcars$hp and mtcars$mpg\nS = 10337, p-value = 5.086e-12\nalternative hypothesis: true rho is not equal to 0\nsample estimates:\n       rho \n-0.8946646 \n```\n\n\n:::\n:::\n\n\nSi l'on veut produire une représentation graphique qui illustre la valeur de *rho*, il pourrait être davantage pertinent de non plus montrer un nuage de points à partir des valeurs des variables mises en lien, mais un nuage de points à partir de leurs rangs respectifs (cf. code ci-dessous et @fig-graphSpearman).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmtcars |>\n  mutate(hp_rank = rank(hp), mpg_rank = rank(mpg)) |>\n  ggplot(aes(x = hp_rank, y = mpg_rank)) +\n  geom_point() +\n  geom_smooth(method = \"lm\", se = FALSE)\n```\n\n::: {.cell-output-display}\n![Graphique pour le coefficient de corrélation de Spearman](bivariate_analyses_files/figure-html/fig-graphSpearman-1.png){#fig-graphSpearman width=90%}\n:::\n:::\n\n\nEn matière d'interprétation, des valeurs de *rho* positives indiqueront que les deux variables mises en lien tendent à augmenter simultanément, on parlera alors de **relation monotone positive**. Dans le cas inverse, des valeurs négatives indiqueront que les deux variables mises en lien tendent à diminuer simultanément, on parlera alors de relation **monotone négative**. À noter cependant que de par son calcul, la valeur de *rho* ne permet pas de renseigner sur la forme de relation qu'il pourrait y avoir entre les valeurs des deux variables (e.g., linéaire ou curvilinéaire par exemple). Ceci est illustré sur la @fig-ranksvvaluesspearman. Sur cette figure, le graphique de gauche montre la relation entre les valeurs des variables $X$ et $Y$, qui est caractérisée par un coefficient de corrélation de Spearman (*rho*) de 1, indiquant donc que la relation est parfaitement monotone positive, sans préjuger de la forme particulière que pourrait présenter la relation. Pour mieux comprendre pourquoi cette valeur de *rho* est de 1, le graphique de droite de la figure montre la relation entre les rangs de ces deux variables $X$ et $Y$. On voit que la relation entre les rangs est effectivement parfaitement linéaire.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Distinction entre la relation observée entre les valeurs (graphique de gauche) et les rangs (graphique de droite) de deux variables](bivariate_analyses_files/figure-html/fig-ranksvvaluesspearman-1.png){#fig-ranksvvaluesspearman width=90%}\n:::\n:::\n\n\n## Relation entre deux variables qualitatives\n\n### Étudier graphiquement la relation\n\nPlusieurs types de graphiques peuvent être envisagés lorsqu'il s'agit de visualiser des données relatives au croisement de deux variables qualitatives. Une première approche consiste à utiliser des graphiques avec barres mises côte-à-côte, comme illustré sur la @fig-groupedBarsFigure, qui a été réalisée à partir du jeu de données `JointSports`, lequel est utilisable après installation et chargement du package `vcd`. `JointSports` contient des données résumées d'effectifs mis en lien avec les modalités de différentes variables qualitatives, comme on aurait pu l'obtenir avec la fonction `count()` dans les derniers exemples du chapitre précédent. La différence qu'il y a avec ces précédents exemples est qu'ici, l'effectif est désigné par la variable `Freq`, alors qu'il s'agissait de la variable `n` auparavant. Pour information, `JointSports` contient les données d'une enquête s'étant intéressée, en 1983 et 1985, aux opinions d'étudiants danois de 16 à 19 ans sur la pratique sportive mixte.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(vcd)\n\n# Reconfiguration de l'ordre des modalités de la variable opinion, et calcul \n# des effectifs totaux pour les catégories étudiées\n\nJointSports_new <- \n  JointSports |>\n  mutate(opinion = fct_relevel(opinion, \n                               \"very bad\", \n                               \"bad\", \n                               \"indifferent\", \n                               \"good\", \n                               \"very good\"),\n         gender = fct_relevel(gender, \"Girl\", \"Boy\")) |>\n  group_by(gender, opinion) |>\n  summarise(Freq = sum(Freq))\n\n# Création des graphiques\nA <- \n  ggplot(data = JointSports_new, aes(x = gender, y = Freq, fill = opinion)) +\n  geom_bar(stat = \"identity\",  position = \"dodge\") +\n  scale_fill_brewer(palette = \"Greens\") +\n  theme(legend.position = \"right\") +\n  ggtitle(\"A : Mise en avant de la comparaison des opinions\")\n\nB <- \n  ggplot(data = JointSports_new, aes(x = opinion, y = Freq, fill = gender)) +\n  geom_bar(stat = \"identity\",  position = \"dodge\") +\n  theme(legend.position = \"right\") +  \n  ggtitle(\"B : Mise en avant de la comparaison des genres\")\n```\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n![Exemples de diagramme en barres mises côte-à-côte](bivariate_analyses_files/figure-html/fig-groupedBarsFigure-1.png){#fig-groupedBarsFigure width=100%}\n:::\n:::\n\n\nPour pouvoir réaliser le graphique `A` de la @fig-groupedBarsFigure, il a fallu indiquer dans la fonction `ggplot()`, grâce à l'argument `x = `, la variable dont on voulait voir les modalités en abscisses, et il a fallu renseigner pour les ordonnées, à l'aide de l'argument `y = `, la variable contenant les effectifs correspondants, le tout toujours à l'intérieur de la fonction `aes()`. Étant donné que les données à montrer le long de l'axe des ordonnées sont explicitement indiquées avec `Freq`, il convient d'indiquer à l'intérieur de la fonction `geom_bar()` l'argument `stat = \"identity\"`, ce qui contraint à déterminer la hauteur des barres en fonction des valeurs de la variable `Freq`. À l'intérieur de la fonction `ggplot()`, plus exactement au niveau de la fonction `aes()`, c'est l'argument `fill = opinion` qui a permis d'indiquer qu'on voulait des couleurs de remplissage différentes selon les modalités de la variable `opinion`. Enfin, c'est grâce à l'argument `position = \"dodge\"`, à l'intérieur de la fonction `geom_bar()`, que l'on a pu obtenir des barres mises côte-à-côte, et non pas de manière empilée. Une logique similaire a été utilisée pour le graphique `B` en modifiant le code de telle sorte à ce que la distinction de l'information avec des couleurs différentes se fasse avec la variable `gender`, et non plus `opinion`.\n\nLes graphiques `A` et `B` de la @fig-groupedBarsFigure montrent l'importance de la configuration du graphique en fonction des comparaisons que l'on veut principalement faire, et donc du message que l'on veut prioritairement délivrer. Un principe qui peut guider la conception du graphique est le fait qu'il est plus facile de comparer des barres qui sont mises juste côte-à-côte. Sur la base de ce principe, le graphique `A` de la @fig-groupedBarsFigure permet de comparer plus facilement les diverses opinions relevées pour les garçons d'un côté et pour les filles de l'autre, alors que le graphique `B` permet de comparer plus facilement les réponses provenant des deux genres et cela pour chaque type d'opinion. Comme indiqué par Wilke [-@wilkeFundamentalsDataVisualization2018], les types de graphiques illustrés avec les graphiques `A` et `B` de la @fig-groupedBarsFigure peuvent parfois se voir attribuer le reproche que s'il est relativement facile de lire les informations encodées par des positions (cf. ligne de base sur les graphiques), il peut être être difficile de lire les informations encodées par une couleur dont la signification est indiquée en légende, car cela demande un effort mental supplémentaire de garder en tête la signification de la légende lorsqu'on lit le graphique. Pour palier ce problème, qui, selon Wilke [-@wilkeFundamentalsDataVisualization2018], est au final une affaire de goût, on pourrait utiliser la fonction `facet_wrap()` pour créer une figure telle que la @fig-groupedBarsUpgraded. Cette figure reprend la logique du graphique `A` de la @fig-groupedBarsFigure, avec un besoin de légende pour la variable `opinion` qui n'existe plus car la fonction `facet_wrap()` a permis de montrer les diagrammes en barres pour les deux genres de manière séparée, dans des encarts différents, et avec chacun leur propre axe des abscisses relatif aux modalités de la variable `opinion`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = JointSports_new, aes(x = opinion, y = Freq)) +\n  geom_bar(stat = \"identity\") +\n  facet_wrap(. ~ gender)\n```\n\n::: {.cell-output-display}\n![Diagrammes en barres côte-à-côte séparés selon une variable qualitative](bivariate_analyses_files/figure-html/fig-groupedBarsUpgraded-1.png){#fig-groupedBarsUpgraded width=100%}\n:::\n:::\n\n\nDans certains cas, on peut vouloir comparer les effectifs relatifs aux modalités d'une première variable qualitative avec des barres mises côte-à-côte, et n'utiliser la seconde variable qualitative que pour avoir un peu d'éléments de contexte \"à l'intérieur\" des effectifs affichés pour la première variable qualitative. La @fig-stackedBarsBiv illustre ce cas de figure où la hauteur des barres sert prioritairement à comparer les effectifs relatifs à diverses opinions, et la coloration des barres sert à fournir une idée de la répartition (hommes / femmes dans l'exemple) dans les réponses, sans pourtant avoir l'ambition de comparer cette répartition facilement d'un type d'opinion à un autre.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nJointSports_new |>\n  ggplot(aes(x = opinion, y = Freq, fill = gender)) +\n  geom_bar(stat = \"identity\") +\n  geom_text(aes(label = Freq), size = 3, position = position_stack(vjust = 0.5))\n```\n\n::: {.cell-output-display}\n![Exemple de diagramme en barres empilées](bivariate_analyses_files/figure-html/fig-stackedBarsBiv-1.png){#fig-stackedBarsBiv width=90%}\n:::\n:::\n\n\nLes graphiques présentés dans cette sous-partie montrent des valeurs d'effectifs, mais selon l'objectif, il pourrait être aussi envisagé d'utiliser ces graphiques pour montrer des proportions. Cela dit, il existe d'autres visualisations possibles des proportions pour visualiser le lien entre deux variables qualitatives. Ces visualisations peuvent être consultées dans l'ouvrage en ligne de Wilke [-@wilkeFundamentalsDataVisualization2018].\n\n\n### Étudier numériquement la relation\n\n#### Tableau de contingence\n\nLorsqu'il s'agit de mener une étude numérique de la relation entre deux variables qualitatives, une première démarche à mettre en oeuvre est de récapituler numériquement les effectifs qui correspondent au croisement des deux variables. Pour cela, la fonction `table()` intégrée à R de base s'avère très pratique. Cependant, cette fonction requiert d'utiliser le jeu de données initial complet (i.e., avec toutes les observations), ce qui n'est pas le cas du jeu de données `JointSports` que nous avons utilisé précédemment, car ce dernier contient des effectifs déjà récapitulés par modalité de variable. Pour pouvoir illustrer le fonctionnement de la fonction `table()` avec les informations du jeu de données `JointSports`, j'ai donc crée un jeu de données complet qui, une fois résumé comme c'est le cas plus haut avec `JointSports`, donnerait les mêmes résultats. Ce nouveau jeu de données se nomme `JointSports_full`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Création du jeu de données JointSports_full\n\nid <- rep(1 : sum(JointSports$Freq))\nyear <- c(rep(\"1983\", 656), rep(\"1985\", 615))\ngrade <- c(rep(\"1st\", 350), rep(\"3rd\", 306), rep(\"1st\", 354), rep(\"3rd\", 261))\ngender <- c(rep(\"Boy\", 134), rep(\"Girl\", 216), rep(\"Boy\", 115), \n            rep(\"Girl\", 191),  rep(\"Boy\", 157), rep(\"Girl\", 197), \n            rep(\"Boy\", 104), rep(\"Girl\", 157))\nopinion <- c(\n  rep(\"very good\", 31), rep(\"good\", 51), rep(\"indifferent\", 38), \n  rep(\"bad\", 10), rep(\"very bad\", 4), \n  rep(\"very good\", 103), rep(\"good\", 67), rep(\"indifferent\", 29), \n  rep(\"bad\", 15), rep(\"very bad\", 2), \n  rep(\"very good\", 23), rep(\"good\", 39), rep(\"indifferent\", 36), \n  rep(\"bad\", 15), rep(\"very bad\", 2), \n  rep(\"very good\", 61), rep(\"good\", 72), rep(\"indifferent\", 39), \n  rep(\"bad\", 16), rep(\"very bad\", 3), \n  rep(\"very good\", 41), rep(\"good\", 67), rep(\"indifferent\", 35), \n  rep(\"bad\", 12), rep(\"very bad\", 2), \n  rep(\"very good\", 77), rep(\"good\", 80), rep(\"indifferent\", 27), \n  rep(\"bad\", 10), rep(\"very bad\", 3), \n  rep(\"very good\", 31), rep(\"good\", 31), rep(\"indifferent\", 31), \n  rep(\"bad\", 4), rep(\"very bad\", 7), \n  rep(\"very good\", 52), rep(\"good\", 70), rep(\"indifferent\", 28), \n  rep(\"bad\", 4), rep(\"very bad\", 3)\n  )\n\nJointSports_full <- \n  data.frame(id = id, \n             year = year, \n             grade = grade, \n             gender = gender, \n             opinion = opinion) |>\n  mutate(opinion = fct_relevel(opinion, \n                               \"very bad\", \n                               \"bad\", \n                               \"indifferent\", \n                               \"good\", \n                               \"very good\"))\n```\n:::\n\n\nUne fois que l'on a un jeu de données complet sous la main, il est possible de créer ce qu'on appelle un **tableau de contingence**, c'est-à-dire ici un tableau qui récapitule numériquement les effectifs à la croisée des deux variables qui nous intéressent. Pour faire cela, on peut utiliser la fonction `table()` en suivant différentes méthodes montrées ci-dessous. (Le code montré ci-dessous aboutit aux mêmes informations que celles montrées sur la @fig-stackedBarsBiv ci-avant.)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 1ère méthode\ntab <- \n  with(JointSports_full,\n       table(opinion, gender))\n\n# 2ème méthode\ntab <- table(JointSports_full$opinion, JointSports_full$gender)\n\n# Visualisation du tableau de contingence\ntab\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             \n              Boy Girl\n  very bad     15   11\n  bad          41   45\n  indifferent 140  123\n  good        188  289\n  very good   126  293\n```\n\n\n:::\n:::\n\n\nUn tableau de contingence permet donc de comparer des effectifs en fonction de plusieurs modalités et variables à la fois. Le problème, lorsqu'on utilise des effectifs, est que certaines comparaisons peuvent être difficiles à faire lorsque les effectifs totaux liés aux différentes modalités ne sont pas comparables. Par exemple, dans le résultat montré ci-dessus, l'effectif total des filles est de 761 alors que celui des garçons est de 510, ce qui rend difficile la comparaison des garçons et des filles pour les différents types d'opinion recensés dans l'enquête danoise présentée plus haut. C'est pour cela qu'il convient, dans certains cas, de calculer les proportions correspondant à ces différents effectifs. Pour ce faire, on peut :\n\n- Utiliser la fonction `prop.table()`, qui va convertir en proportions les effectifs montrés plus haut en considérant l'effectif total de tout le tableau :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nround(prop.table(tab) * 100, digits = 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             \n                Boy  Girl\n  very bad     1.18  0.87\n  bad          3.23  3.54\n  indifferent 11.01  9.68\n  good        14.79 22.74\n  very good    9.91 23.05\n```\n\n\n:::\n:::\n\n\n- Utiliser la fonction `lprop()` du package `questionr`, qui va convertir en proportions les effectifs montrés plus haut en considérant l'effectif total de chaque ligne du tableau :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(questionr)\nlprop(tab)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             \n              Boy   Girl  Total\n  very bad     57.7  42.3 100.0\n  bad          47.7  52.3 100.0\n  indifferent  53.2  46.8 100.0\n  good         39.4  60.6 100.0\n  very good    30.1  69.9 100.0\n  Ensemble     40.1  59.9 100.0\n```\n\n\n:::\n:::\n\n\n- Utiliser la fonction `cprop()` du package `questionr`, qui va convertir en proportions les effectifs montrés plus haut en considérant l'effectif total de chaque colonne du tableau :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(questionr)\ncprop(tab)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             \n              Boy   Girl  Ensemble\n  very bad      2.9   1.4   2.0   \n  bad           8.0   5.9   6.8   \n  indifferent  27.5  16.2  20.7   \n  good         36.9  38.0  37.5   \n  very good    24.7  38.5  33.0   \n  Total       100.0 100.0 100.0   \n```\n\n\n:::\n:::\n\n\nIl convient de noter que les proportions données par ces différentes fonctions doivent être utilisées selon les comparaisons que l'on veut faire. L'analyse descriptive consiste alors à voir si, tant d'un point de vue graphique que numérique, on observe des différences de scores particulières entre les modalités d'une variable qualitative en fonction des modalités de l'autre variable qualitative. Si l'on considère le dernier tableau de résultats ci-dessus, on peut par exemple observer une très légère tendance à ce que les garçons soient davantage polarisés, par rapport aux filles, sur des opinions négatives vis-à-vis des pratiques sportives mixtes, alors que les filles seraient légèrement plus polarisées que les garçons sur des opinions positives, ce qui n'empêche pas que, pour les deux genres, il y a une polarisation principale sur des opinions neutres à positives.\n\nSi les proportions permettent en principe de mieux comparer les effectifs de sous-groupes (e.g., les opinions par groupe de genre dans l'exemple ci-dessus) lorsque les effectifs des groupes parents sont de tailles différentes (comme c'est le cas pour les groupes de genre dans l'exemple ci-dessus), il convient tout de même de faire attention aux conclusions que l'on tire lorsqu'on s'en tient à une analyse globale, car ces conclusions dépendent de la manière dont les individus des groupes parents sont répartis dans chacun des sous-groupes. Un exemple connu qui permet d'illustrer cette vigilance à avoir lorsqu'on étudie le croisement de variables qualitatives est le cas du taux de réussite des femmes à l'université de Berkeley en 1973, qui apparaissait bien inférieur à celui des hommes lorsqu'on considérait les taux de réussite par genre à l'échelle de l'ensemble de l’université [@bickelSexBiasGraduate1975], avec 30.3 % de réussite chez les femmes contre 44.5 % de réussite chez les hommes (cf. @fig-taballUCBA).\n\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n![Taux de réussite des étudiants femmes et hommes à l'Université de Berkeley en 1973, approche globale (Bickel et al., 1975)](bivariate_analyses_files/figure-html/fig-taballUCBA-1.png){#fig-taballUCBA width=90%}\n:::\n:::\n\n\nToutefois, une analyse par département permettait de voir que les taux de réussite des femmes étaient en réalité supérieurs voire nettement supérieurs à ceux des hommes dans la plupart des départements (cf. @fig-tabdepUCBA).\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Taux de réussite des étudiants femmes et hommes à l'Université de Berkeley en 1973, approche par département (Bickel et al., 1975)](bivariate_analyses_files/figure-html/fig-tabdepUCBA-1.png){#fig-tabdepUCBA width=100%}\n:::\n:::\n\n\nCette situation, qui peut paraître étonnante, illustre à nouveau ce qu'on appelle un paradoxe de Simpson. Dans le cas présent, l'apparent paradoxe s'explique par le fait que les femmes avaient en proportion davantage candidaté que les hommes dans des départements où le taux de réussite global était moins bon. Ceci est illustré sur la @fig-distriUCBA.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Mise en avant du département d'inscription comme facteur confondant dans l'étude du lien entre le genre et le taux de réussite à l'Université de Berkeley en 1973 (Bickel et al., 1975)](bivariate_analyses_files/figure-html/fig-distriUCBA-1.png){#fig-distriUCBA width=100%}\n:::\n:::\n\n\nAutrement dit, les hommes se retrouvaient avec un pourcentage de réussite global bien meilleur que celui des femmes seulement parce que, comparativement aux femmes, les hommes s'étaient en proportion davantage engagés dans les départements où les taux de réussite étaient bien meilleurs.\n\nAu-delà du tableau de contingence, plusieurs outils statistiques sont disponibles pour quantifier le lien entre les modalités de deux variables qualitatives [@janeEffectSizesConfidence2023]. On s’intéresse ici plus spécifiquement au coefficient Phi ($\\Phi$), au $V$ de Cramer, à la différence de risque, au risque relatif, et au rapport des cotes. À noter que tous ces indices statistiques, excepté le $V$ de Cramer, sont essentiellement faits pour analyser le lien entre deux variables qualitatives dont l’une ne présenterait que deux modalités (on parle alors de variable binaire).\n\n#### Coefficient Phi\n\nLe coefficient $\\Phi$ est une valeur qui peut être comprise entre -1 et 1 (ou entre 0 et 1 selon les manières de l'obtenir) et indique la force de la relation entre deux variables qualitatives binaires. Toutefois, seule la valeur absolue (entre 0 et 1 donc) est à interpréter. Le signe (si jamais différents signes peuvent apparaître selon le calcul utilisé) ne fait que renseigner sur la diagonale du tableau de contingence où les individus sont davantage polarisés. Pour comprendre comment $\\Phi$ peut être calculé, prenons les tableaux de contingence montrés ci-dessous (@fig-PhiContTables) : \n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Tableaux de contingence schématiques pour comprendre le calcul de Phi](bivariate_analyses_files/figure-html/fig-PhiContTables-1.png){#fig-PhiContTables fig-align='center' width=90%}\n:::\n:::\n\n\nOn note sur ces tableaux qu’une valeur absolue de $\\Phi$ élevée sera attendue dans le cas où il y aura relativement beaucoup d’individus dans une diagonale et relativement peu d’individus dans l’autre diagonale (cf. tableaux du milieu et de droite ci-dessus). Si l'on prend comme base l'un des tableaux de contingence montrés ci-dessus, la formule du coefficient $\\Phi$ est la suivante [@janeEffectSizesConfidence2023] : \n\n$$\\Phi = \\frac{(n_{11} \\cdot n_{22}) - (n_{21} \\cdot n_{12})}{\\sqrt{(n_{11} + n_{21}) \\cdot (n_{12} + n_{22}) \\cdot (n_{11} + n_{12}) \\cdot (n_{21} + n_{22})}}$$\nUne autre formule pour calculer $\\Phi$ (donnant systématiquement la valeur absolue du coefficient) pourrait être aussi la suivante [@janeEffectSizesConfidence2023] : \n\n$$\\Phi = \\sqrt{\\frac{\\chi^2}{n}},$$ \n\navec $\\chi^2$ la statistique \"chi-carré\" et $n$ le nombre total d'individus. Pour calculer $\\Phi$ dans R, on peut utiliser la fonction `phi()` du package `effectsize` :\n\n::: {.cell}\n\n```{.r .cell-code}\ntab <- table(mtcars$am, mtcars$vs)\neffectsize::phi(tab)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPhi (adj.) |       95% CI\n-------------------------\n0.00       | [0.00, 1.00]\n\n- One-sided CIs: upper bound fixed at [1.00].\n```\n\n\n:::\n:::\n\n\n#### $V$ de Cramer\n\nLe $V$ de Cramer est la forme généralisée de la force d’association entre deux variables qualitatives. Il peut donc être calculé à partir d’un tableau de contingence de n’importe quelle taille, prendre des valeurs absolues entre 0 et 1, et est ainsi l’équivalent du coefficient $\\Phi$ dans le cas d’un tableau de contingence 2 x 2 (2 variables qualitatives x 2 modalités chacune). La formule du $V$ de Cramer est la suivante [@janeEffectSizesConfidence2023] : \n\n$$V = \\sqrt{\\frac{\\chi^2}{n \\cdot (k-1)}},$$ \navec $\\chi^2$ la statistique « chi-carré », $n$ le nombre total d’individus, et $k$ le nombre de modalités de la variable qui a le moins de modalités. Pour calculer le $V$ de Cramer dans R, on peut utiliser la fonction `cramers_v()` du package `effectsize` :\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntab <- table(JointSports_full$gender, JointSports_full$opinion)\neffectsize::cramers_v(tab)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCramer's V (adj.) |       95% CI\n--------------------------------\n0.17              | [0.11, 1.00]\n\n- One-sided CIs: upper bound fixed at [1.00].\n```\n\n\n:::\n:::\n\n\n#### Différence de risque\n\nLa différence de risque est une différence de proportions. La notion de risque peut ne pas être très pertinente pour certains contextes, mais elle l’est particulièrement dans un contexte de santé. Pour comprendre le calcul du risque puis de la différence de risque, regardons le tableau ci-dessous (@fig-RiskContTables).\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Tableau de contingence schématique pour comprendre le calcul des risques et des cotes](bivariate_analyses_files/figure-html/fig-RiskContTables-1.png){#fig-RiskContTables fig-align='center' width=70%}\n:::\n:::\n\n\nDans le tableau ci-dessus, chaque case contenant un « n » est un effectif. Si l’on désire connaître le risque d’être malade dans le groupe contrôle ($p_C$) et dans le groupe traité ($p_T$), on fait les calculs suivants : \n\n$$p_C = \\frac{n_{C1}}{n_{C0} + n_{C1}}$$\n\n$$p_T = \\frac{n_{T1}}{n_{T0} + n_{T1}}$$\n\nLa différence de risque d'être malade pour le groupe contrôle par rapport au groupe traité de l'exemple, notée $DR$, est alors :\n\n$$p_C - p_T $$\nAvec R, la différence de risque peut être obtenue avec le package `riskCommunicator`. Pour utiliser le package `riskCommunicator`, il faut bien sûr l'installer et ensuite le charger :\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(riskCommunicator)\n```\n:::\n\n\nPour l'exemple, chargeons le jeu de données `cvdd` associé au package `riskCommunicator`:\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(cvdd)\n```\n:::\n\n\nIl s'agit d'un jeu de données avec plusieurs variables qualitatives, dont plusieurs sont plus précisément binaires (i.e., qui ne contiennent que deux modalités). Admettons que l'on souhaiterait connaître la différence de risque de mortalité cardiovasculaire (`cvd_dh`) sur une période de suivi donnée, cela en fonction de si l'on a développé une hypertension ou non (`HYPERTEN`). Pour cela, on peut utiliser la fonction `gComp()` du package `riskCommunicator` comme suit :\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngComp(data = cvdd, X = \"HYPERTEN\", Y = \"cvd_dth\", outcome.type = \"binary\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFormula: \ncvd_dth ~ HYPERTEN \n\nParameter estimates: \n                            HYPERTEN1_v._HYPERTEN0 Estimate (95% CI)\nRisk Difference                                 0.132 (0.098, 0.159)\nRisk Ratio                                      1.411 (1.275, 1.527)\nOdds Ratio                                      1.753 (1.505, 1.977)\nNumber needed to treat/harm                                    7.559\n```\n\n\n:::\n:::\n\n\nDans le résultat obtenu, la différence de risque est de 0.132, soit 13.2 %. À ce stade, il est fondamental de comprendre que le résultat obtenu dépend de la manière dont les modalités sont ordonnées dans les variables de type facteur utilisées pour faire les calculs. Regardons comment les modalités sont organisées pour les variables qui nous concernent : \n\n::: {.cell}\n\n```{.r .cell-code}\nlevels(cvdd$HYPERTEN)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"0\" \"1\"\n```\n\n\n:::\n\n```{.r .cell-code}\nlevels(cvdd$cvd_dth)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"0\" \"1\"\n```\n\n\n:::\n:::\n\n\nOn remarque qu'à chaque fois, \"0\" est la première modalité, et \"1\" est la seconde modalité. C'est important de le savoir pour interpréter le résultat ensuite car la fonction `gComp()` calcule par défaut la différence de risque en faisant le risque de présenter la modalité 2 de la variable Y quand on a la modalité 2 de la variable X (ici le risque de mourir quand on est hypertendu) moins le risque de présenter la modalité 2 de la variable Y quand on a la modalité 1 de la variable X (ici le risque de mourir quand on n'est pas hypertendu). On peut d'ailleurs vérifier le calcul manuellement :\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Obtention d'un tableau de contingence avec proportions\ntab <- table(cvdd$HYPERTEN, cvdd$cvd_dth)\nrisks <- questionr::lprop(tab)\ncolnames(risks) <- c(\"vivant\", \"mort\", \"total\")\nrownames(risks) <- c(\"non-hypertendu\", \"hypertendu\", \"total\")\nrisks\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                \n                 vivant mort  total\n  non-hypertendu  67.8   32.2 100.0\n  hypertendu      54.6   45.4 100.0\n  total           58.2   41.8 100.0\n```\n\n\n:::\n\n```{.r .cell-code}\n# Calcul de la différence de risque de mortalité \n# chez les hypertendus vs non-hypertendus (en %)\n45.4-32.2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 13.2\n```\n\n\n:::\n:::\n\n\n#### Risque relatif\n\nLe risque relatif, noté $RR$, reprend les mêmes informations que celles utilisées pour la différence de risque (${p_T}$ et ${p_C}$). La différence est qu’il ne s’agit plus d’une différence, mais d’un rapport entre les risques présentés par les groupes comparés. Sa formule pour comparer le groupe contrôle au groupe traité dans notre exemple débuté plus haut est la suivante :\n\n$$RR = \\frac{{p_C}}{{p_T}}$$\nAvec R, le risque relatif peut  être obtenu avec le package `riskCommunicator` tel que montré pour le calcul de la différence de risque, en faisant toujours bien attention à quel risque est divisé par quel risque selon l'analyse qui est réellement souhaitée. Dans notre exemple débuté plus haut, il s'agit du même calcul que pour la différence de risque sauf qu'il ne s'agit plus d'un signe moins mais d'une division. Les résultats obtenus plus haut avec l'exemple de la différence de risque montrent aussi le risque relatif, qui est tel que le risque de mourir chez les hypertendus est 1.41 fois plus élevé que chez les non-hypertendus.\n\n#### Rapports des cotes\n\nLe rapport des cotes, noté $OR$ pour *Odds ratio* en anglais, est une statistique dont le calcul peut à nouveau se comprendre à l’aide d’un tableau de contingence. Si l’on reprend le tableau de la Figure @fig-RiskContTables, on peut dire que la cote pour le fait d’être en bonne santé versus être malade dans le groupe contrôle est $n_{C0}$/$n_{C1}$ et la cote pour le fait d’être en bonne santé versus malade dans le groupe traité est $n_{T0}$/$n_{T1}$. Le rapport des cotes pour le groupe contrôle versus le groupe traité dans ce cas-là peut se calculer comme ceci : \n\n$$ OR=  \\frac{n_{C0} / n{_{C1}}}{n_{T0} / n{_{T1}}}$$\n\nLe rapport des cotes est toujours ≥0. Une valeur en-dessous de 1 signifie « moins de chances/risques », une valeur de 1 signifie « chances/risques équivalent(e)s », et une valeur au-dessus de 1 signifie « plus de chances ou de risques ». Le chiffre obtenu renseigne toujours sur un niveau de chances pour le groupe au numérateur par rapport au niveau de chances concernant le groupe au dénominateur (cf. formule ci-dessus). Avec R, le rapport des cotes peut  être obtenu avec le package `riskCommunicator` tel que montré pour le calcul de la différence de risque, en faisant cette fois attention à quelle cote est divisée par quelle cote selon l'analyse qui est réellement souhaitée. Dans notre exemple débuté plus haut, le rapport des cotes est de 1.75. Cela signifie ici que la cote pour le fait de mourir (versus le fait de vivre) est 1.75 fois plus élevée quand on est hypertendu que lorsqu'on ne l'est pas. Pour comprendre le calcul, on peut le refaire manuellement : \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Obtention d'un tableau de contingence avec effectifs\ntab <- table(cvdd$HYPERTEN, cvdd$cvd_dth)\ncolnames(tab) <- c(\"vivant\", \"mort\")\nrownames(tab) <- c(\"non-hypertendu\", \"hypertendu\")\ntab\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                \n                 vivant mort\n  non-hypertendu    781  371\n  hypertendu       1685 1403\n```\n\n\n:::\n\n```{.r .cell-code}\n# Calcul des cotes pour les \"chances\" de mourir selon le groupe d'appartenance\ncote_hypertendus <- 1403/1685\ncote_non_hypertendus <- 371/781\n\n# Calcul du rapport des cotes\nOR <- cote_hypertendus / cote_non_hypertendus\nOR\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.75281\n```\n\n\n:::\n:::\n\n\n## Résumé\n\n* La relation entre deux variables quantitatives peut être étudiée graphiquement à l'aide d'un nuage de points et numériquement à l'aide, notamment, du coefficient de corrélation de Pearson (*r*) ou du coefficient de corrélation de Spearman (*rho*). Le premier caractérise le degré de lien linéaire entre les valeurs des deux variables, alors que le second caractérise le lien linéaire entre les rangs des deux variables.\n* La relation entre deux variables qualitatives peut être étudiée graphiquement à l'aide de diagrammes en barres mises côte-à-côte ou empilées, et numériquement à l'aide du croisement d'effectifs ou de proportions, du coefficient Phi, du V de Cramer, de la différence de risque, du risque relatif, ou encore du rapport des cotes selon le contexte. \n",
    "supporting": [
      "bivariate_analyses_files\\figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"site_libs/tabwid-1.1.3/tabwid.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/tabwid-1.1.3/tabwid.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}